// GENERATED by scripts/build.mjs -- do not edit by hand.

// src/index.ts
import { createServer } from "node:http";
import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

// src/auth.ts
import { readFileSync } from "node:fs";
var LOOPBACK = /* @__PURE__ */ new Set(["127.0.0.1", "::1", "::ffff:127.0.0.1"]);
function normalizeAddress(value) {
  const raw = String(value ?? "");
  if (raw === "") return "";
  if (raw.startsWith("[")) {
    const end = raw.indexOf("]");
    return end >= 0 ? raw.slice(1, end) : raw;
  }
  const lastColon = raw.lastIndexOf(":");
  if (lastColon > 0 && raw.indexOf(":") === lastColon) return raw.slice(0, lastColon);
  return raw;
}
function isLoopbackRequest(request) {
  return LOOPBACK.has(normalizeAddress(request.socket?.remoteAddress));
}
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
function bearerFrom(request) {
  const raw = request.headers?.authorization;
  const value = Array.isArray(raw) ? raw[0] : raw;
  if (typeof value !== "string") return "";
  const match = /^Bearer\s+(.+)$/i.exec(value.trim());
  return match === null ? "" : match[1].trim();
}
function checkAuth(request, token, requireLoopback = true) {
  if (requireLoopback && !isLoopbackRequest(request)) {
    return { ok: false, status: 401, reason: "non-loopback origin" };
  }
  if (token === "") {
    return { ok: false, status: 503, reason: "bridge token unavailable" };
  }
  const presented = bearerFrom(request);
  if (presented === "" || !safeEqual(presented, token)) {
    return { ok: false, status: 401, reason: "invalid token" };
  }
  return { ok: true, status: 200, reason: "" };
}
function readToken(direct, filePath, envName) {
  if (direct !== "") return direct;
  if (filePath !== "") {
    const fromFile = readTokenFile(filePath);
    if (fromFile !== "") return fromFile;
  }
  if (envName === "") return "";
  const value = process.env[envName];
  return typeof value === "string" ? value.trim() : "";
}
function readTokenFile(path) {
  try {
    return readFileSync(path, "utf8").trim();
  } catch {
    return "";
  }
}

// src/body.ts
var HttpError = class extends Error {
  status;
  constructor(status, message) {
    super(message);
    this.name = "HttpError";
    this.status = status;
  }
};
function readBody(request, maxBytes) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    let settled = false;
    const fail = (error) => {
      if (settled) return;
      settled = true;
      reject(error);
    };
    request.on("data", (chunk) => {
      if (settled) return;
      total += chunk.length;
      if (total > maxBytes) {
        request.destroy();
        fail(new HttpError(413, "request body too large"));
        return;
      }
      chunks.push(chunk);
    });
    request.on("end", () => {
      if (settled) return;
      settled = true;
      const buffer = Buffer.concat(chunks);
      try {
        resolve(new TextDecoder("utf-8", { fatal: true }).decode(buffer));
      } catch {
        reject(new HttpError(400, "body is not valid UTF-8"));
      }
    });
    request.on("error", (error) => fail(error));
    request.on("aborted", () => fail(new HttpError(400, "request aborted")));
  });
}

// src/channel.ts
var MCP_CHANNEL = "@oblivion/core/mcp";
var MCP_API_VERSION = 1;
function channelKey() {
  return Symbol.for(MCP_CHANNEL);
}
function emptyDescription(reason) {
  return {
    present: false,
    apiVersion: MCP_API_VERSION,
    owner: "",
    version: "",
    tools: [],
    ready: false,
    reason
  };
}
function readSlots() {
  try {
    const scope = globalThis;
    const raw = scope[channelKey()];
    if (!(raw instanceof Map)) return [];
    const slots = [];
    for (const value of raw.values()) {
      if (value === null || typeof value !== "object") continue;
      slots.push(value);
    }
    return slots;
  } catch {
    return [];
  }
}
function isReady(slot) {
  try {
    return slot.endpoint?.describe?.()?.ready === true;
  } catch {
    return false;
  }
}
function pickSlot(slots) {
  if (slots.length === 0) return { slot: null, reason: "\u672A\u627E\u5230\u901A\u9053" };
  const compatible = slots.filter((slot) => slot.apiVersion === MCP_API_VERSION);
  if (compatible.length === 0) {
    const actual = slots.map((slot) => String(slot.apiVersion)).join(", ");
    return {
      slot: null,
      reason: `\u5951\u7EA6\u7248\u672C\u4E0D\u5339\u914D\uFF1A\u671F\u671B ${MCP_API_VERSION}\uFF0C\u5B9E\u9645 ${actual}`
    };
  }
  const ready = compatible.filter((slot) => isReady(slot));
  const pool = ready.length > 0 ? ready : compatible;
  let newest = pool[0];
  for (const slot of pool) {
    if (typeof slot.at === "number" && slot.at >= newest.at) newest = slot;
  }
  return { slot: newest, reason: "" };
}
function resolveOblivionEndpoint() {
  try {
    const slot = pickSlot(readSlots()).slot;
    return slot === null ? null : slot.endpoint;
  } catch {
    return null;
  }
}
function describeOblivionChannel() {
  try {
    const slots = readSlots();
    if (slots.length === 0) return emptyDescription("\u672A\u627E\u5230\u901A\u9053");
    const { slot, reason } = pickSlot(slots);
    if (slot === null) return emptyDescription(reason);
    const info = slot.endpoint.describe();
    return {
      present: true,
      apiVersion: info.apiVersion,
      owner: info.owner,
      version: info.version,
      tools: Array.isArray(info.tools) ? info.tools : [],
      ready: info.ready === true,
      reason: ""
    };
  } catch (error) {
    return emptyDescription(`\u8BFB\u53D6\u901A\u9053\u5931\u8D25\uFF1A${error instanceof Error ? error.message : String(error)}`);
  }
}

// src/config.ts
var DEFAULT_PORT = 42081;
var DEFAULT_HOST = "127.0.0.1";
var DEFAULT_PATH = "/oblivion/mcp";
var DEFAULT_MAX_BODY_BYTES = 1048576;
var DEFAULT_ALLOWED_ORIGINS = [
  "chrome-extension://koealbifonogjljlppjngjnaejemdjhp"
];
var DEFAULT_CONFIG = {
  port: DEFAULT_PORT,
  host: DEFAULT_HOST,
  path: DEFAULT_PATH,
  // 直给与文件默认都为空：默认仍走环境变量，保持向后兼容。
  // 需要绕开环境继承时，在 profile patch 里填这两项之一。
  token: "",
  tokenFile: "",
  tokenEnv: "OBLIVION_BRIDGE_TOKEN",
  requireLoopback: true,
  maxBodyBytes: DEFAULT_MAX_BODY_BYTES,
  allowedOrigins: DEFAULT_ALLOWED_ORIGINS,
  debug: false
};
function resolveConfig(raw) {
  const merged = { ...DEFAULT_CONFIG, ...raw ?? {} };
  return {
    port: normalizePort(merged.port),
    host: typeof merged.host === "string" && merged.host !== "" ? merged.host : DEFAULT_HOST,
    path: normalizePath(merged.path),
    token: typeof merged.token === "string" ? merged.token.trim() : DEFAULT_CONFIG.token,
    tokenFile: typeof merged.tokenFile === "string" ? merged.tokenFile.trim() : DEFAULT_CONFIG.tokenFile,
    tokenEnv: typeof merged.tokenEnv === "string" ? merged.tokenEnv.trim() : DEFAULT_CONFIG.tokenEnv,
    requireLoopback: merged.requireLoopback !== false,
    maxBodyBytes: normalizePositiveInt(merged.maxBodyBytes, DEFAULT_MAX_BODY_BYTES),
    allowedOrigins: Array.isArray(merged.allowedOrigins) ? merged.allowedOrigins.filter((value) => typeof value === "string" && value !== "") : DEFAULT_ALLOWED_ORIGINS,
    debug: merged.debug === true
  };
}
function normalizePort(value) {
  const port = typeof value === "number" ? value : Number(value);
  if (!Number.isInteger(port) || port < 1 || port > 65535) return DEFAULT_PORT;
  return port;
}
function normalizePath(value) {
  if (typeof value !== "string" || value === "") return DEFAULT_PATH;
  const withSlash = value.startsWith("/") ? value : `/${value}`;
  return withSlash.length > 1 && withSlash.endsWith("/") ? withSlash.slice(0, -1) : withSlash;
}
function normalizePositiveInt(value, fallback) {
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isInteger(n) || n < 1) return fallback;
  return n;
}

// src/index.ts
var name = "@oblivion/http-bridge";
var inject = [];
var MARKER = "[oblivion-http-bridge] loaded";
var VERSION = true ? "0.1.1" : "0.0.0-unknown";
function credentialSource(config) {
  if (config.token !== "") return "config.token";
  if (config.tokenFile !== "") return `file:${config.tokenFile}`;
  return `env:${config.tokenEnv}`;
}
function corsHeaders(origin, allowedOrigins) {
  if (origin === "" || !allowedOrigins.includes(origin)) return {};
  return {
    "access-control-allow-origin": origin,
    "access-control-allow-methods": "POST, OPTIONS",
    "access-control-allow-headers": "authorization, content-type",
    "access-control-max-age": "600",
    vary: "origin"
  };
}
function writeHeartbeat(ctx, path, config, gotConfig) {
  try {
    const heartbeat = {
      writtenBy: "@oblivion/http-bridge",
      at: (/* @__PURE__ */ new Date()).toISOString(),
      pid: process.pid,
      version: VERSION,
      // apply 收到的什么
      gotConfig: gotConfig === void 0 ? "undefined" : Object.keys(gotConfig).join(","),
      resolvedPort: config.port,
      credentialSource: credentialSource(config),
      tokenEnvValue: process.env[config.tokenEnv] === void 0 ? "undefined" : `len:${String(process.env[config.tokenEnv]).length}`,
      // 依赖面：空 inject 是「永远能激活」的保证（见文件头）
      inject: [],
      // 通道现状：端点缺席时这里是 present:false + 中文原因
      mcpEndpoint: describeOblivionChannel(),
      ctxKeys: (() => {
        try {
          return Object.keys(ctx).join(",");
        } catch {
          return "(throws)";
        }
      })()
    };
    const dir = join(homedir(), ".oblivion");
    mkdirSync(dir, { recursive: true });
    writeFileSync(path, JSON.stringify(heartbeat, null, 2), "utf8");
  } catch (error) {
    ctx.logger?.warn?.(
      `[oblivion-bridge] heartbeat \u5199\u5165\u5931\u8D25\uFF1A${error instanceof Error ? error.message : String(error)}`
    );
  }
}
function apply(rawCtx, rawConfig) {
  const ctx = rawCtx;
  const config = resolveConfig(rawConfig);
  const heartbeatPath = join(homedir(), ".oblivion", "bridge-heartbeat.json");
  let endpointSeen = false;
  const log = (message) => {
    if (config.debug) ctx.logger?.info?.(`[oblivion-bridge] ${message}`);
  };
  writeHeartbeat(ctx, heartbeatPath, config, rawConfig);
  if (config.token === "" && config.tokenFile === "" && config.tokenEnv === "") {
    ctx.logger?.info?.("[oblivion-bridge] \u672A\u914D\u7F6E\u4EFB\u4F55\u51ED\u636E\u6765\u6E90\uFF0C\u6865\u63A5\u7AEF\u70B9\u5DF2\u7981\u7528");
    return;
  }
  const server = createServer((request, response) => {
    void handleRequest(ctx, config, request, response, log, {
      refreshHeartbeat: () => {
        if (endpointSeen) return;
        endpointSeen = true;
        writeHeartbeat(ctx, heartbeatPath, config, rawConfig);
        log(`endpoint ready \xB7 ${JSON.stringify(describeOblivionChannel())}`);
      }
    }).catch((error) => {
      const reason = error instanceof Error ? error.message : String(error);
      ctx.logger?.warn?.(`[oblivion-bridge] unhandled: ${reason}`);
      if (!response.headersSent) {
        response.writeHead(500, { "content-type": "text/plain; charset=utf-8" });
      }
      response.end("internal error");
    });
  });
  server.on("error", (error) => {
    ctx.logger?.warn?.(`[oblivion-bridge] server error: ${error.message}`);
  });
  server.listen(config.port, config.host, () => {
    ctx.logger?.info?.(
      `[oblivion-bridge] listening \xB7 http://${config.host}:${config.port}${config.path} \xB7 \u51ED\u636E\u6765\u6E90=${credentialSource(config)}`
    );
    const channel = describeOblivionChannel();
    if (!channel.present) {
      ctx.logger?.info?.(`[oblivion-bridge] MCP \u7AEF\u70B9\u5C1A\u672A\u5C31\u7EEA\uFF1A${channel.reason}\uFF08\u8BF7\u6C42\u4F1A\u5982\u5B9E\u56DE 503\uFF09`);
    }
  });
  ctx.effect(
    () => () => {
      server.close();
    },
    "oblivion-http-bridge: http server"
  );
  console.log(MARKER);
}
async function handleRequest(ctx, config, request, response, log, hooks) {
  const url = request.url ?? "";
  const pathname = url.split("?")[0] ?? "";
  const healthPath = `${config.path}/health`;
  if (pathname !== config.path && pathname !== healthPath) {
    response.writeHead(404, { "content-type": "text/plain; charset=utf-8", "content-length": "9" });
    response.end("not found");
    return;
  }
  const origin = String(request.headers.origin ?? "");
  const cors = corsHeaders(origin, config.allowedOrigins);
  const send = (status, body, extra = {}) => {
    const payload = typeof body === "string" ? body : JSON.stringify(body);
    response.writeHead(status, {
      "content-type": typeof body === "string" ? "text/plain; charset=utf-8" : "application/json; charset=utf-8",
      "content-length": String(Buffer.byteLength(payload)),
      "cache-control": "no-store",
      ...cors,
      ...extra
    });
    response.end(payload);
  };
  if (request.method === "OPTIONS") {
    response.writeHead(204, { ...cors, "content-length": "0" });
    response.end();
    return;
  }
  if (pathname === healthPath) {
    if (request.method !== "GET") {
      send(405, "method not allowed", { allow: "GET" });
      return;
    }
    send(200, {
      ok: true,
      version: VERSION,
      port: config.port,
      path: config.path,
      uptimeMs: Math.round(performance.now()),
      endpoint: describeOblivionChannel()
    });
    return;
  }
  if (request.method !== "POST") {
    send(405, "method not allowed", { allow: "POST, OPTIONS" });
    return;
  }
  const token = readToken(config.token, config.tokenFile, config.tokenEnv);
  const verdict = checkAuth(request, token, config.requireLoopback);
  if (!verdict.ok) {
    log(`auth: rejected (${verdict.reason})`);
    send(verdict.status, "unauthorized");
    return;
  }
  const endpoint = resolveOblivionEndpoint();
  if (endpoint === null) {
    const reason = describeOblivionChannel().reason;
    log(`endpoint unavailable: ${reason}`);
    send(503, {
      jsonrpc: "2.0",
      id: null,
      error: { code: -32603, message: `oblivion core endpoint unavailable: ${reason}` }
    });
    return;
  }
  hooks.refreshHeartbeat();
  let rawBody;
  try {
    rawBody = await readBody(request, config.maxBodyBytes);
  } catch (error) {
    if (error instanceof HttpError) {
      send(error.status, error.message);
      return;
    }
    log(`body: ${error instanceof Error ? error.message : String(error)}`);
    send(400, "bad request body");
    return;
  }
  try {
    const result = await endpoint.handle(rawBody, log);
    if (result === void 0 || result === null) {
      response.writeHead(204, { ...cors, "content-length": "0" });
      response.end();
      return;
    }
    send(200, result);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    log(`mcp: unhandled ${reason}`);
    send(200, { jsonrpc: "2.0", id: null, error: { code: -32603, message: reason } });
  }
}
var index_default = { name, inject, apply };
export {
  apply,
  index_default as default,
  inject,
  name
};
