#!/usr/bin/env node
/**
 * @oblivion/http-bridge 构建脚本（esbuild）。
 *
 * 单入口：src/index.ts → lib/index.js
 *
 * ## external 的决定
 *
 * 本包**不 import 任何 @deepseek-ai/* 包**（刻意为之，见 src/types.ts 注释），
 * 所以 HOST_PROVIDED 列表是空的 —— 产物是自包含的，只需要 Node 内置模块。
 *
 * 这与 @oblivion/core 不同：core 必须把 `@deepseek-ai/dsh-tools` 标 external，
 * 因为 defineTool 的参数校验发生在宿主运行时，打进产物会出现两份 schema 行为。
 * 本包没有这个问题。
 */

import { mkdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LIB = join(ROOT, 'lib');

/** 由 Host 运行时提供的框架包，绝不打进产物。本包一个都不用。 */
const HOST_PROVIDED = [];

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const version = pkg.version;

mkdirSync(LIB, { recursive: true });

await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: ['node22'],
  outfile: join(LIB, 'index.js'),
  external: HOST_PROVIDED,
  define: { __OBLIVION_BRIDGE_VERSION__: JSON.stringify(version) },
  banner: { js: '// GENERATED by scripts/build.mjs -- do not edit by hand.' },
  logLevel: 'warning',
});

// 刻意**不**写 `lib/VERSION`：产物里再存一份版本号就是第二个来源
// （`tools/check-workspace.ps1` 的 Assert-NoLibVersion 会直接判失败）。
const size = readFileSync(join(LIB, 'index.js'), 'utf8').length;
process.stdout.write('@oblivion/http-bridge v' + version + ': lib/index.js (' + size + ' B)\n');
