#!/usr/bin/env node
/**
 * @oblivion/core 构建脚本（esbuild）。
 *
 * 两个入口：
 *   src/index.ts    → lib/index.js    插件本体（Cordis Loader 加载）
 *   src/testkit.ts  → lib/testkit.js  纯函数探针（自检与单元测试用）
 *
 * 本插件是 Host 侧认知层，没有浏览器半边 —— 所以这里不出现
 * __ModuleLoader__ / React external 那类客户端包装。
 *
 * ## external 的决定
 *
 * `@deepseek-ai/dsh-tools` 必须标为 external，理由不是体积而是**一致性**：
 * 它导出 defineTool 与 schema 编译器，参数校验发生在 Host 运行时。
 * 打进产物就会出现「构建时副本 vs 宿主副本」两份 schema 行为，
 * 一旦分叉就是「明明校验过却报错」这种最难查的问题。
 * 实测体量对照：打进产物 330 KB，标 external 后 43 KB。
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LIB = join(ROOT, 'lib');

/** 由 Host 运行时提供的框架包，绝不打进产物。 */
const HOST_PROVIDED = [
  '@deepseek-ai/dsh-tools',
  '@deepseek-ai/dsh-llm',
  '@deepseek-ai/dsh-util-values',
  '@deepseek-ai/cordis',
];

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const version = pkg.version;

mkdirSync(LIB, { recursive: true });

for (const entry of ['index', 'testkit']) {
  await build({
    entryPoints: [join(ROOT, 'src', entry + '.ts')],
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: ['node22'],
    outfile: join(LIB, entry + '.js'),
    external: HOST_PROVIDED,
    define: { __OBLIVION_CORE_VERSION__: JSON.stringify(version) },
    banner: { js: '// GENERATED by scripts/build.mjs -- do not edit by hand.' },
    logLevel: 'warning',
  });
}

writeFileSync(join(LIB, 'VERSION'), version + '\n', 'utf8');
const size = readFileSync(join(LIB, 'index.js'), 'utf8').length;
process.stdout.write('@oblivion/core v' + version + ': lib/index.js (' + size + ' B) + lib/testkit.js\n');