// GENERATED by scripts/build.mjs -- do not edit by hand.

// src/config.ts
var DEFAULT_CONFIG = {
  dataRoot: "~/.oblivion/data",
  /**
   * 文档根（所有者裁定 2026-10-06）：直接写进既有的知识库，不再单开 `oblivion_docs/`。
   * 用正斜杠书写：Windows 上 `path.isAbsolute('C:/…')` 成立，`expandHome()` 原样放行，
   * 且写进 YAML 时不需要转义反斜杠。
   */
  mdRoot: "C:/Library/\u90A3\u4E9B\u6E10\u6E10\u88AB\u9057\u5FD8",
  mdClassify: {
    // 问答沉淀（我们的捕获来源是 session；qa_loop 是设计书的原始命名，一并兼容）
    session: "01_\u95EE\u7B54\u6C89\u6DC0",
    qa_loop: "01_\u95EE\u7B54\u6C89\u6DC0",
    // 设计书 §25.3 的其余分类（后续文档导入/创作能力落地后直接生效）
    doc: "00_\u5BFC\u5165\u6587\u4EF6",
    wiki: "02_Wiki\u9875\u9762",
    content_creator: "03_\u521B\u4F5C\u4EA7\u7269"
  },
  /**
   * 价值阈值 —— **已按实测重标定，不要改回设计书原值 0.5**。
   *
   * 实测分布（heuristicScore）：
   *   真实 233 字技术回答（有来源 + 结构 + 代码）  0.370
   *   500 字普通回答                              ~0.42
   *   900 字低信息密度（大量重复）                 0.454
   *   "ok"                                      0.113
   *
   * 原值 0.5 落在「真实回答之上、重复文本之下」，会让正常问答**一律被丢弃**
   * ——症状是插件装好了但知识库永远为空，且不报错。0.30 把「ok 类噪声」
   * 挡住，同时放行正常回答。这是端到端自检用例抓出来的，改动请同步更新
   * test/ 与 scripts/selfcheck.mjs 的断言。
   */
  semanticThreshold: 0.85,
  valueThreshold: 0.3,
  enablePerspective: true,
  enableFeedback: true,
  perspectiveMinSessions: 4,
  perspectiveMinConfidence: 0.3,
  perspectiveMinMisses: 3,
  perspectiveDeepDiveTurns: 5,
  // §25.4 双模式闸门（设计书原值）
  perspectiveActiveSessionMax: 3,
  perspectiveMinQuestionLength: 10,
  perspectiveDeepTriggerRepeats: 3,
  perspectiveDeepMinCandidates: 3,
  perspectiveDeepSessionMax: 5,
  // §25.7 保留期（读取时惰性裁剪，满足「无定时任务」约束）
  feedbackRetentionDays: 90,
  graphInitialWeight: 0.3,
  graphReinforceDelta: 0.05,
  graphWeightCap: 1,
  graphDecayBase: 0.95,
  graphDecayPeriodDays: 30,
  feedbackTuneThreshold: 3,
  promptSectionOrder: 50,
  maxPerspectivePerTurn: 2,
  /**
   * L3 最低答案长度 —— **设计书 §25.1 原值 5**（旧实现用 20，等于把 L3 当成了价值闸门）。
   * 5 字以下直接判无意义；「短但可能有用」留给 L4 价值评估（`valueThreshold`）兜底。
   */
  minAnswerLength: 5,
  logPrefix: "[oblivion-core]"
};

// src/feedback/index.ts
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join as join2 } from "node:path";

// src/util/paths.ts
import { homedir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";
function expandHome(p) {
  const home = homedir();
  if (!p) return home;
  if (p === "~") return home;
  if (p.startsWith("~/") || p.startsWith("~\\")) return join(home, p.slice(2));
  return isAbsolute(p) ? p : resolve(p);
}

// src/util/time.ts
var MS_PER_DAY = 864e5;
function now() {
  return Date.now();
}
function ageDays(from, at = now()) {
  return Math.max(0, (at - from) / MS_PER_DAY);
}
function newId(at = now()) {
  const rand = Math.random().toString(36).slice(2, 4).padEnd(2, "0");
  return `ts-${at.toString(36)}-${rand}`;
}
function isoDate(at) {
  return new Date(at).toISOString().slice(0, 10);
}

// src/feedback/tuner.ts
async function tune(entries, target, profile, threshold) {
  const same = entries.filter((e) => e.target === target && e.signal !== 0);
  if (same.length < threshold) return false;
  const recent = same.slice(-threshold);
  const allUp = recent.every((e) => e.signal === 1);
  const allDown = recent.every((e) => e.signal === -1);
  if (!allUp && !allDown) return false;
  let weight = 0;
  for (let i = 1; i <= recent.length; i += 1) weight += 1 / i;
  const confidence = Math.min(0.8, weight / threshold);
  if (allUp) {
    await profile.update({
      receptive_dimensions: [target],
      inquiry_style: { primary: target, secondary: "unknown", confidence }
    });
  } else {
    await profile.update({ resistant_dimensions: [target] });
  }
  return true;
}

// src/feedback/index.ts
var MS_PER_DAY2 = 864e5;
function registerFeedback(ctx, config, profile) {
  const path = join2(expandHome(config.dataRoot), "feedback.json");
  let prunedTotal = 0;
  async function load() {
    try {
      const parsed = JSON.parse(await readFile(path, "utf8"));
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }
  async function save(entries) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, JSON.stringify(entries, null, 2) + "\n", "utf8");
  }
  async function loadPruned() {
    const entries = await load();
    const cutoff = now() - config.feedbackRetentionDays * MS_PER_DAY2;
    const kept = entries.filter((e) => typeof e.created_at === "number" && e.created_at >= cutoff);
    const dropped = entries.length - kept.length;
    if (dropped > 0) {
      prunedTotal += dropped;
      await save(kept);
      ctx.logger?.info?.(
        config.logPrefix + " feedback \u4FDD\u7559\u671F\u88C1\u526A\uFF1A%d \u6761\u8D85\u8FC7 %d \u5929",
        dropped,
        config.feedbackRetentionDays
      );
    }
    return kept;
  }
  ctx.effect(() => () => {
  }, "oblivion-core: feedback teardown");
  return {
    async record(args) {
      const entries = await loadPruned();
      const recorded = {
        id: newId(),
        target: args.target,
        signal: args.signal,
        context: args.context ?? "",
        created_at: now()
      };
      entries.push(recorded);
      await save(entries);
      const tuned = args.signal !== 0 ? await tune(entries, args.target, profile, config.feedbackTuneThreshold) : false;
      return { recorded, tuned };
    },
    all: loadPruned,
    reset: () => save([]),
    stats: async () => ({
      total: (await loadPruned()).length,
      pruned: prunedTotal,
      retentionDays: config.feedbackRetentionDays
    })
  };
}

// src/graph/index.ts
import { mkdir as mkdir2, readFile as readFile2, writeFile as writeFile2 } from "node:fs/promises";
import { join as join3 } from "node:path";

// src/graph/decay.ts
function effectiveWeight(edge, cfg, at = now()) {
  const age = ageDays(edge.last_reinforced_at, at);
  const decayed = edge.weight * Math.pow(cfg.base, age / Math.max(1, cfg.periodDays));
  return Math.min(edge.weight, Math.max(0, decayed));
}
function reinforce(edge, cfg, at = now()) {
  return {
    ...edge,
    weight: Math.min(cfg.cap, edge.weight + cfg.delta),
    last_reinforced_at: at,
    reinforce_count: edge.reinforce_count + 1
  };
}

// src/graph/index.ts
function extractEntities(text, cap = 24) {
  const out = /* @__PURE__ */ new Set();
  const re = /[A-Za-z][\w.-]{2,}|[\u4e00-\u9fff]{2,8}/g;
  for (const m of text.matchAll(re)) {
    const t = m[0].toLowerCase();
    if (t.length < 2 || t.length > 32) continue;
    out.add(t);
    if (out.size >= cap) break;
  }
  return [...out];
}
function edgeKey(a, b) {
  return a < b ? a + "\0" + b : b + "\0" + a;
}
function registerGraph(ctx, config) {
  const root = expandHome(config.dataRoot);
  const statePath = join3(root, "graph.json");
  const eventPath = join3(root, "graph-events.json");
  let edges = /* @__PURE__ */ new Map();
  let log = [];
  const loaded = (async () => {
    try {
      const raw = JSON.parse(await readFile2(statePath, "utf8"));
      edges = new Map(raw.map((e) => [edgeKey(e.source_id, e.target_id), e]));
    } catch {
      edges = /* @__PURE__ */ new Map();
    }
    try {
      log = JSON.parse(await readFile2(eventPath, "utf8"));
    } catch {
      log = [];
    }
  })();
  async function persist() {
    await mkdir2(root, { recursive: true });
    await writeFile2(statePath, JSON.stringify([...edges.values()], null, 2) + "\n", "utf8");
    await writeFile2(eventPath, JSON.stringify(log.slice(-2e3), null, 2) + "\n", "utf8");
  }
  function neighborsOf(id, limit) {
    const at = now();
    const cfg = { base: config.graphDecayBase, periodDays: config.graphDecayPeriodDays };
    return [...edges.values()].filter((e) => e.source_id === id || e.target_id === id).map((e) => ({
      id: e.source_id === id ? e.target_id : e.source_id,
      effective: effectiveWeight(e, cfg, at)
    })).sort((a, b) => b.effective - a.effective).slice(0, limit);
  }
  ctx.effect(() => () => {
    edges.clear();
    log = [];
  }, "oblivion-core: graph teardown");
  return {
    async recordCooccurrence(qa) {
      await loaded;
      const entities = extractEntities(qa.question + "\n" + qa.answer);
      if (entities.length < 2) return 0;
      const at = now();
      let changed = 0;
      for (let i = 0; i < entities.length; i += 1) {
        for (let j = i + 1; j < entities.length; j += 1) {
          const a = entities[i];
          const b = entities[j];
          const key = edgeKey(a, b);
          const existing = edges.get(key);
          if (existing) {
            const next = reinforce(existing, {
              delta: config.graphReinforceDelta,
              cap: config.graphWeightCap
            }, at);
            edges.set(key, next);
            log.push({
              edge_id: key,
              event_type: "reinforce",
              weight_delta: next.weight - existing.weight,
              created_at: at
            });
          } else {
            edges.set(key, {
              source_id: a < b ? a : b,
              target_id: a < b ? b : a,
              weight: config.graphInitialWeight,
              last_reinforced_at: at,
              reinforce_count: 0
            });
            log.push({
              edge_id: key,
              event_type: "create",
              weight_delta: config.graphInitialWeight,
              created_at: at
            });
          }
          changed += 1;
        }
      }
      if (changed > 0) await persist();
      return changed;
    },
    async neighbors(id, limit = 20) {
      await loaded;
      const at = now();
      const cfg = { base: config.graphDecayBase, periodDays: config.graphDecayPeriodDays };
      return [...edges.values()].filter((e) => e.source_id === id || e.target_id === id).map((e) => ({ ...e, effective: effectiveWeight(e, cfg, at) })).sort((a, b) => b.effective - a.effective).slice(0, limit);
    },
    edges: () => [...edges.values()],
    events: () => [...log],
    neighborsOf
  };
}

// src/util/hash.ts
import { createHash } from "node:crypto";
function sha1(input) {
  return createHash("sha1").update(input, "utf8").digest("hex");
}
function normalizeForHash(text) {
  return text.toLowerCase().replace(/[\s\u3000]+/g, " ").replace(/[，。、；：！？,.;:!?"'\u201c\u201d\u2018\u2019()（）\[\]【】《》<>`*_\-—]+/g, "").trim();
}
function shortHash(input) {
  return sha1(input).slice(0, 12);
}

// src/knowledge/search.ts
var STOP = /* @__PURE__ */ new Set([
  "the",
  "and",
  "for",
  "with",
  "that",
  "this",
  "from",
  "are",
  "was",
  "were",
  "\u4F60",
  "\u6211",
  "\u4ED6",
  "\u5979",
  "\u7684",
  "\u4E86",
  "\u662F",
  "\u5728",
  "\u548C",
  "\u5C31",
  "\u90FD",
  "\u800C",
  "\u53CA",
  "\u4E0E",
  "\u6216",
  "\u4E00\u4E2A",
  "\u8FD9\u4E2A",
  "\u90A3\u4E2A",
  "\u4EC0\u4E48",
  "\u600E\u4E48",
  "\u5982\u4F55",
  "\u53EF\u4EE5",
  "\u9700\u8981"
]);
function tokenize(text) {
  const out = [];
  for (const chunk of text.toLowerCase().split(/[^\p{L}\p{N}]+/u)) {
    if (!chunk) continue;
    if (/[\u3040-\u30ff\u3400-\u9fff]/.test(chunk)) {
      for (const ch of chunk) if (!STOP.has(ch)) out.push(ch);
      if (chunk.length >= 2) out.push(chunk);
      continue;
    }
    if (chunk.length >= 2 && !STOP.has(chunk)) out.push(chunk);
  }
  return out;
}
function jaccard(a, b) {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const t of a) if (b.has(t)) inter += 1;
  return inter / (a.size + b.size - inter);
}
var KnowledgeIndex = class {
  items = [];
  postings = /* @__PURE__ */ new Map();
  rebuild(items) {
    this.items = items.filter((i) => i.status !== "archived");
    this.postings.clear();
    this.items.forEach((item, idx) => {
      const tokens = /* @__PURE__ */ new Set([
        ...tokenize(item.title),
        ...tokenize(item.content),
        ...item.tags.flatMap((t) => tokenize(t))
      ]);
      for (const t of tokens) {
        let set = this.postings.get(t);
        if (!set) this.postings.set(t, set = /* @__PURE__ */ new Set());
        set.add(idx);
      }
    });
  }
  get size() {
    return this.items.length;
  }
  all() {
    return this.items;
  }
  byId(id) {
    return this.items.find((i) => i.id === id);
  }
  search(query, limit = 10) {
    const tokens = [...new Set(tokenize(query))];
    if (tokens.length === 0) return [];
    const candidateHits = /* @__PURE__ */ new Map();
    for (const t of tokens) {
      for (const idx of this.postings.get(t) ?? []) {
        let set = candidateHits.get(idx);
        if (!set) candidateHits.set(idx, set = /* @__PURE__ */ new Set());
        set.add(t);
      }
    }
    const hits = [];
    for (const [idx, matched] of candidateHits) {
      const item = this.items[idx];
      let score = matched.size / tokens.length;
      const titleTokens = new Set(tokenize(item.title));
      for (const t of matched) {
        if (titleTokens.has(t)) score += 0.2;
        if (item.tags.some((tag) => tag.toLowerCase().includes(t))) score += 0.2;
      }
      hits.push({ item, score, matched: [...matched] });
    }
    return hits.sort((a, b) => b.score - a.score).slice(0, limit);
  }
  /** 共现扩展：检索之后把强邻居也带出来，这是「关键词 + 共现图」的图那一半。 */
  expandByGraph(seedIds, neighborsOf, limit = 3) {
    const out = [];
    const seen = new Set(seedIds);
    for (const id of seedIds) {
      for (const n of neighborsOf(id, limit)) {
        if (seen.has(n.id)) continue;
        seen.add(n.id);
        const item = this.byId(n.id);
        if (item) out.push(item);
      }
    }
    return out;
  }
};

// src/knowledge/evaluate.ts
function heuristicScore(qa) {
  const answer = qa.answer;
  const lengthScore = Math.min(1, answer.length / 800);
  const richnessScore = Math.min(1, new Set(tokenize(answer)).size / 160);
  const sourceScore = Math.min(1, qa.sources.length / 2);
  const hasCode = /```|\b(function|class|const|let|SELECT|FROM|npm|pnpm|dshx|docker)\b/i.test(answer) ? 1 : 0;
  const hasNumber = /\d/.test(answer) ? 1 : 0;
  const hasStructure = /(^|\n)\s*(#{2,4}\s|[-*]\s|\d+[.)]\s|\|)/.test(answer) ? 1 : 0;
  const hasTopic = qa.topicHint ? 1 : 0;
  return lengthScore * 0.25 + richnessScore * 0.2 + sourceScore * 0.2 + hasCode * 0.1 + hasNumber * 0.1 + hasStructure * 0.05 + hasTopic * 0.1;
}
async function evaluate(qa, ctx = {}) {
  const base = heuristicScore(qa);
  if (!ctx.llmScore) return base;
  const llm = await ctx.llmScore(qa).catch(() => void 0);
  if (typeof llm !== "number" || Number.isNaN(llm)) return base;
  return Math.min(1, Math.max(0, Math.min(1, Math.max(0, llm)) * 0.7 + base * 0.3));
}

// src/knowledge/filter.ts
function isOblivionOriginated(qa) {
  return qa.sources.some((s) => s.type === "qa_loop" || s.ref.startsWith("oblivion:"));
}
function passesRules(qa, config) {
  if (isOblivionOriginated(qa)) return { pass: false, reason: "oblivion-originated" };
  if (qa.sources.length === 0) return { pass: false, reason: "no-source" };
  return checkL3Rules(qa, config);
}
var MEANINGLESS_TOKENS = /* @__PURE__ */ new Set([
  "\u65E0",
  "\u6CA1\u6709",
  "\u6682\u65E0",
  "\u4E0D\u77E5\u9053",
  "\u4E0D\u6E05\u695A",
  "\u6D4B\u8BD5",
  "\u8BD5\u8BD5",
  "\u5360\u4F4D",
  "\u7565",
  "\u540C\u4E0A",
  "test",
  "testing",
  "asdf",
  "qwer",
  "aaa",
  "zzz",
  "todo",
  "tbd",
  "na",
  "n/a"
]);
var PLEASANTRY_TOKENS = /(?:辛苦了|太感谢|感谢你|谢谢你|多谢|谢谢|感谢|好的|好嘞|行吧|可以|收到|明白|了解|懂了|辛苦了|thanks|thank you|thx|okay|ok|got it|nice|cool|嗯+|哦+|啊+|哈哈+|呵呵)/gi;
var FILLER_TOKENS = /(?:你|您|啦|了|的|呀|啊|哦|咯|喽|哈|吧|呢|嘛|~)/g;
var PLEASANTRY_MAX_CHARS = 24;
function isPleasantryOnly(answer) {
  const trimmed = answer.trim();
  if (trimmed === "" || trimmed.length > PLEASANTRY_MAX_CHARS) return false;
  const stripped = trimmed.replace(/[\s\p{P}\p{S}]/gu, "");
  if (stripped === "") return false;
  const leftover = stripped.replace(PLEASANTRY_TOKENS, "").replace(FILLER_TOKENS, "");
  return leftover === "";
}
var UNKNOWN_ANSWER = /^\s*(?:我|我们)?\s*(?:也)?\s*(?:不知道|不清楚|不了解|不确定|无法确定|无从得知|不会|i\s*don'?t\s*know|not\s*sure|no\s*idea)/i;
var UNKNOWN_HEAD_CHARS = 40;
function isMeaninglessOnly(answer) {
  const withoutPunctuation = answer.replace(/[\s\p{P}\p{S}]/gu, " ").trim();
  if (withoutPunctuation === "") return true;
  const tokens = withoutPunctuation.split(/\s+/).filter((t) => t.length > 0);
  if (tokens.length === 0) return true;
  return tokens.every((t) => t.length <= 1 || MEANINGLESS_TOKENS.has(t.toLowerCase()));
}
function checkL3Rules(qa, config) {
  const answer = qa.answer.trim();
  if (answer.length < config.minAnswerLength) return { pass: false, reason: "answer-too-short" };
  if (isMeaninglessOnly(answer)) return { pass: false, reason: "meaningless-only" };
  if (UNKNOWN_ANSWER.test(answer.slice(0, UNKNOWN_HEAD_CHARS))) return { pass: false, reason: "contains-unknown" };
  if (isPleasantryOnly(answer)) return { pass: false, reason: "pleasantry-only" };
  return { pass: true };
}
async function fourLayerFilter(qa, config, deps) {
  if (await deps.exactDuplicate(qa)) {
    return { pass: false, action: "duplicate", reason: "exact hash match" };
  }
  const sim = await deps.semanticSimilar(qa, config.semanticThreshold);
  if (sim.action === "duplicate") {
    return { pass: false, action: "duplicate", reason: "semantic duplicate", existing: sim.existing };
  }
  if (sim.action === "conflict") {
    return { pass: false, action: "conflict", reason: "conflicts with existing item", existing: sim.existing };
  }
  const rules = passesRules(qa, config);
  if (!rules.pass) {
    return { pass: false, action: "ignored", reason: rules.reason };
  }
  const score = await evaluate(qa, deps.evaluateContext);
  if (score < config.valueThreshold) {
    return { pass: false, action: "ignored", score, reason: "below value threshold" };
  }
  return {
    pass: true,
    action: sim.action === "appended" ? "appended" : "created",
    score,
    existing: sim.existing
  };
}
function compareByOverlap(qa, candidates, threshold) {
  const qaTokens = new Set(tokenize(qa.question + "\n" + qa.answer));
  let best;
  for (const item of candidates) {
    const ratio = jaccard(qaTokens, new Set(tokenize(item.title + "\n" + item.content)));
    if (!best || ratio > best.ratio) best = { item, ratio };
  }
  if (!best || best.ratio <= 0) return { action: "new" };
  if (best.ratio >= threshold) {
    const contradicts = flipSignals(qa.answer) !== flipSignals(best.item.content) && best.ratio > 0.7;
    return contradicts ? { action: "conflict", existing: best.item, ratio: best.ratio } : { action: "duplicate", existing: best.item, ratio: best.ratio };
  }
  if (best.ratio >= threshold * 0.6 && qa.answer.length > best.item.content.length) {
    return { action: "appended", existing: best.item, ratio: best.ratio };
  }
  return { action: "new", ratio: best.ratio };
}
function flipSignals(text) {
  const negations = (text.match(/不|没有|无法|禁止|不能|cannot|not\b|never|no longer/gi) ?? []).length;
  return negations % 2 === 0 ? "affirm" : "negate";
}

// src/knowledge/store.ts
import { mkdir as mkdir3, readFile as readFile3, readdir, writeFile as writeFile3 } from "node:fs/promises";
import { join as join4 } from "node:path";
var KnowledgeStore = class {
  constructor(root) {
    this.root = root;
  }
  root;
  get conflictsRoot() {
    return join4(this.root, "conflicts");
  }
  async init() {
    await mkdir3(this.root, { recursive: true });
    await mkdir3(this.conflictsRoot, { recursive: true });
  }
  async loadAll() {
    const files = await readdir(this.root).catch(() => []);
    const items = [];
    for (const f of files) {
      if (!f.endsWith(".json")) continue;
      try {
        const raw = await readFile3(join4(this.root, f), "utf8");
        const parsed = JSON.parse(raw);
        if (parsed && typeof parsed.id === "string") items.push(parsed);
      } catch {
      }
    }
    return items;
  }
  async save(item) {
    await this.init();
    await writeFile3(join4(this.root, item.id + ".json"), JSON.stringify(item, null, 2) + "\n", "utf8");
  }
  /** 冲突记录返回文件名，便于在日志/工具输出里指认。 */
  async saveConflict(payload) {
    await this.init();
    const id = "conflict-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 6);
    await writeFile3(join4(this.conflictsRoot, id + ".json"), JSON.stringify(payload, null, 2) + "\n", "utf8");
    return id;
  }
};

// src/knowledge/index.ts
function fingerprint(qa) {
  const sourceKey = qa.sources.map((s) => s.type + ":" + s.ref).sort().join("|");
  return sha1(normalizeForHash(qa.question) + "::" + normalizeForHash(qa.answer) + "::" + sourceKey);
}
function contentFingerprint(question, answer) {
  return sha1(normalizeForHash(question) + "::" + normalizeForHash(answer));
}
function registerKnowledge(ctx, config) {
  const store = new KnowledgeStore(expandHome(config.dataRoot));
  const index = new KnowledgeIndex();
  let touched = [];
  async function loadIndex() {
    await store.init();
    const items = await store.loadAll();
    index.rebuild(items);
    return items;
  }
  async function ensureLoaded() {
    if (index.size === 0) await loadIndex();
  }
  async function exactDuplicate(qa) {
    const items = index.size > 0 ? index.all() : await loadIndex();
    const fp = fingerprint(qa);
    const contentFp = contentFingerprint(qa.question, qa.answer);
    return items.some((i) => {
      if (i.sources.some((s) => s.hash === fp)) return true;
      return contentFingerprint(i.title, i.content) === contentFp;
    });
  }
  async function semanticSimilar(qa, threshold) {
    const items = index.size > 0 ? index.all() : await loadIndex();
    return compareByOverlap(qa, items.filter((i) => i.status === "active"), threshold);
  }
  async function recordConflict(qa, existing) {
    return store.saveConflict({
      detected_at: now(),
      incoming: { question: qa.question, answer: qa.answer, sources: qa.sources },
      existing: { id: existing.id, title: existing.title, content: existing.content },
      policy: "both versions retained; no silent merge"
    });
  }
  async function capture(qa) {
    const result = await fourLayerFilter(qa, config, { exactDuplicate, semanticSimilar });
    if (!result.pass) {
      if (result.action === "conflict" && result.existing) {
        await recordConflict(qa, result.existing);
      }
      touched = [];
      return result;
    }
    const at = now();
    const fp = fingerprint(qa);
    if (result.action === "appended" && result.existing) {
      const existing = result.existing;
      const updated = {
        ...existing,
        content: existing.content + "\n\n---\n\n" + qa.answer,
        sources: mergeSources(existing.sources, qa, fp),
        updated_at: at,
        version: existing.version + 1
      };
      await store.save(updated);
      await loadIndex();
      touched = [updated.id];
      return { ...result, item: updated };
    }
    const item = {
      id: newId(at),
      topic: qa.topicHint ?? deriveTopic(qa),
      title: deriveTitle(qa),
      content: qa.answer,
      sources: mergeSources([], qa, fp),
      tags: deriveTags(qa),
      status: "active",
      created_at: at,
      updated_at: at,
      version: 1
    };
    await store.save(item);
    await loadIndex();
    touched = [item.id];
    return { ...result, item };
  }
  async function query(args) {
    await ensureLoaded();
    const hits = index.search(args.query, args.limit ?? 10);
    return {
      count: hits.length,
      results: hits.map((h) => ({
        id: h.item.id,
        title: h.item.title,
        topic: h.item.topic,
        score: Number(h.score.toFixed(3)),
        matched: h.matched,
        sources: h.item.sources.map((s) => s.type + ":" + s.ref),
        excerpt: h.item.content.slice(0, 240)
      }))
    };
  }
  ctx.effect(() => {
    void loadIndex().catch(() => {
    });
    return () => {
      index.rebuild([]);
      touched = [];
    };
  }, "oblivion-core: initial index load");
  return {
    init: async () => {
      await loadIndex();
    },
    capture,
    query,
    exactDuplicate,
    semanticSimilar,
    recordConflict,
    store,
    index,
    lastTouched: () => touched
  };
}
function deriveTitle(qa) {
  const q = qa.question.split("\n")[0].trim();
  return q.length > 60 ? q.slice(0, 57) + "\u2026" : q || "untitled";
}
function deriveTopic(qa) {
  if (qa.topicHint) return qa.topicHint;
  const m = qa.question.match(/[\p{L}\p{N}_-]{3,20}/gu);
  return m?.[0] ?? "untitled";
}
function mergeSources(existing, qa, fp) {
  const all = [...existing, ...qa.sources];
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const s of all) {
    const key = s.type + ":" + s.ref;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ type: s.type, ref: s.ref, hash: s.hash || fp });
  }
  return out;
}
function deriveTags(qa) {
  const out = /* @__PURE__ */ new Set();
  if (qa.topicHint) out.add(qa.topicHint);
  const tech = /\b(dsh|dshx|cordis|npm|pnpm|docker|sqlite|fts5|json|yaml|api|mcp|wsl2?|arkts|flutter|esbuild|vitest|node|react)\b/gi;
  for (const m of qa.answer.matchAll(tech)) out.add(m[0].toLowerCase());
  for (const m of qa.answer.matchAll(/#([\p{L}\p{N}_-]{2,20})/gu)) out.add(m[1]);
  return [...out].slice(0, 8);
}

// src/perspective/adapter.ts
function adaptStyle(perspectives, profile) {
  if (perspectives.length === 0) return "";
  const wantsDetail = profile.language_style.prefers.includes("detail");
  const lines = perspectives.map((p) => wantsDetail ? "- " + p.text + "\uFF08\u53EF\u5C55\u5F00\uFF09" : "- " + p.text);
  return ["## \u{1F9ED} \u6269\u5C55\u601D\u8003", ...lines].join("\n");
}

// src/perspective/maker.ts
function generatePerspectives(input) {
  const { coverage, misses, config, resistant, stage, deep } = input;
  const limit = Math.max(1, input.max ?? config.maxPerspectivePerTurn);
  const threshold = deep ? 1 : config.perspectiveMinMisses;
  const out = [];
  for (const dim of coverage.missing) {
    if (resistant.includes(dim)) continue;
    const count = misses.get(dim) ?? 0;
    if (count >= threshold) {
      out.push({
        kind: "missing-dimension",
        dimension: dim,
        text: "\u8FD9\u6761\u56DE\u7B54\u6CA1\u6709\u8986\u76D6\u300C" + dim + "\u300D\uFF0C\u800C\u5B83\u5728\u4F60\u6700\u8FD1\u7684\u63D0\u95EE\u91CC\u53CD\u590D\u51FA\u73B0\uFF08" + count + " \u6B21\uFF09\u3002"
      });
    }
  }
  if (deep) {
    for (const dim of coverage.missing) {
      if (out.length >= limit) break;
      if (resistant.includes(dim)) continue;
      if (out.some((p) => p.dimension === dim)) continue;
      out.push({
        kind: "unexplored",
        dimension: dim,
        text: "\u4F60\u8FDE\u7740\u51E0\u8F6E\u90FD\u5728\u540C\u4E00\u4E2A\u7EF4\u5EA6\u4E0A\u8FFD\u95EE\uFF0C\u8FD9\u6761\u56DE\u7B54\u6CA1\u6709\u8986\u76D6\u300C" + dim + "\u300D\u2014\u2014\u6362\u4E2A\u89D2\u5EA6\u770B\u770B\u4F1A\u4E0D\u4F1A\u66F4\u5FEB\u3002"
      });
    }
  }
  if (stage === "observe" && !deep) return out.slice(0, 1);
  if (out.length === 0 && stage === "companion" && coverage.missing.length === 0) {
    out.push({
      kind: "unexplored",
      dimension: "cost",
      text: "\u8FD9\u6B21\u7684\u8986\u76D6\u9762\u6BD4\u8F83\u5B8C\u6574\uFF0C\u552F\u4E00\u6CA1\u78B0\u7684\u662F\u957F\u671F\u6210\u672C\u3002"
    });
  }
  return out.slice(0, limit);
}

// src/perspective/tracker.ts
var DIMENSIONS = [
  "mechanism",
  "procedure",
  "decision",
  "risk",
  "design",
  "cost",
  "maintenance"
];
function pattern(dim) {
  switch (dim) {
    case "mechanism":
      return /原理|机制|因为|所以|根因|mechanism|because/i;
    case "procedure":
      return /步骤|流程|先.*然后|最后|step|first|then/i;
    case "decision":
      return /对比|取舍|权衡|优缺|trade-?off|\bvs\b/i;
    case "risk":
      return /风险|隐患|会失败|坑|risk|danger|failure/i;
    case "design":
      return /架构|分层|模块|接口|design|architect|module/i;
    case "cost":
      return /成本|开销|费用|性能|代价|cost|overhead|latency/i;
    case "maintenance":
      return /维护|升级|迁移|兼容|maintain|upgrade|migrat/i;
  }
}
function analyzeCoverage(question, answer, topic, sessionId) {
  const blob = question + "\n" + answer;
  const covered = [];
  const missing = [];
  for (const dim of DIMENSIONS) {
    if (pattern(dim).test(blob)) covered.push(dim);
    else missing.push(dim);
  }
  return { topic, session_id: sessionId, covered, missing, created_at: Date.now() };
}

// src/perspective/index.ts
function registerPerspective(ctx, config, deps) {
  let queued = "";
  const misses = /* @__PURE__ */ new Map();
  const resistance = /* @__PURE__ */ new Map();
  const records = [];
  let consecutiveDeepDives = 0;
  let lastPrimaryDimension;
  let sameDimensionStreak = 0;
  let sessionQueued = 0;
  const counters = {
    turns: 0,
    queued: 0,
    activeGateHits: 0,
    deepGateHits: 0,
    companionGateHits: 0,
    blockedByConfidence: 0
  };
  function stageOf(n) {
    if (n < config.perspectiveMinSessions) return "observe";
    if (n <= 10) return "probe";
    return "companion";
  }
  function dominantMissing(coverage, resistant) {
    return coverage.missing.find((d) => !resistant.includes(d));
  }
  ctx.effect(() => () => {
    queued = "";
    misses.clear();
    resistance.clear();
    records.length = 0;
    consecutiveDeepDives = 0;
    lastPrimaryDimension = void 0;
    sameDimensionStreak = 0;
    sessionQueued = 0;
  }, "oblivion-core: perspective teardown");
  return {
    pending: () => queued,
    takePending: () => {
      const t = queued;
      queued = "";
      return t;
    },
    async onTurn(info) {
      if (!config.enablePerspective) return;
      counters.turns += 1;
      const profile = await deps.profile.read();
      if (profile.inquiry_style.confidence < config.perspectiveMinConfidence) {
        counters.blockedByConfidence += 1;
        return;
      }
      const coverage = analyzeCoverage(info.question, info.answer, info.topic, info.sessionId);
      records.push(coverage);
      if (records.length > 200) records.shift();
      for (const dim of coverage.missing) {
        misses.set(dim, (misses.get(dim) ?? 0) + 1);
      }
      const resistant = [...resistance.entries()].filter(([, n]) => n >= 2).map(([d]) => d);
      const primary = dominantMissing(coverage, resistant);
      if (primary !== void 0 && primary === lastPrimaryDimension) {
        sameDimensionStreak += 1;
      } else {
        lastPrimaryDimension = primary;
        sameDimensionStreak = primary === void 0 ? 0 : 1;
      }
      const deepSignals = (info.question.match(/\n[-*\d]/g) ?? []).length + (info.question.length > 400 ? 1 : 0);
      consecutiveDeepDives = deepSignals >= 2 ? consecutiveDeepDives + 1 : 0;
      const deepGate = (sameDimensionStreak >= config.perspectiveDeepTriggerRepeats || consecutiveDeepDives >= config.perspectiveDeepDiveTurns) && sessionQueued < config.perspectiveDeepSessionMax;
      const activeGate = profile.sessions_observed <= config.perspectiveActiveSessionMax && info.question.trim().length >= config.perspectiveMinQuestionLength && (info.sources ?? 1) >= 1;
      const stage = stageOf(profile.sessions_observed);
      const companionGate = stage === "companion" && [...misses.values()].some((n) => n >= config.perspectiveMinMisses);
      if (!deepGate && !activeGate && !companionGate) return;
      if (deepGate) counters.deepGateHits += 1;
      else if (activeGate) counters.activeGateHits += 1;
      else counters.companionGateHits += 1;
      const wantCandidates = deepGate ? Math.max(config.perspectiveDeepMinCandidates, config.maxPerspectivePerTurn) : config.maxPerspectivePerTurn;
      const perspectives = generatePerspectives({
        profile,
        coverage,
        misses,
        config,
        stage,
        resistant,
        max: wantCandidates,
        deep: deepGate
      });
      if (perspectives.length === 0 && consecutiveDeepDives >= config.perspectiveDeepDiveTurns) {
        perspectives.push({
          kind: "to-verify",
          dimension: "assumption",
          text: "\u8FDE\u7EED\u6DF1\u6316\u82E5\u5E72\u8F6E\u4E86\uFF0C\u662F\u5426\u8BE5\u56DE\u5934\u9A8C\u8BC1\u4E00\u4E2A\u524D\u7F6E\u5047\u8BBE\uFF1F"
        });
      }
      const text = adaptStyle(perspectives, profile);
      if (text) {
        queued = text;
        sessionQueued += 1;
        counters.queued += 1;
      }
    },
    recordResistance: (dimension) => {
      resistance.set(dimension, (resistance.get(dimension) ?? 0) + 1);
    },
    coverage: () => [...records],
    stats: () => ({ ...counters })
  };
}

// src/prompt.ts
var OBLIVION_SYSTEM_PROMPT = [
  "## Oblivion \u8BA4\u77E5\u966A\u4F34\u89C4\u5219",
  "",
  "- \u8868\u8FBE\uFF1A\u8868\u683C\u4F18\u5148\u3001\u7ED3\u8BBA\u5148\u884C\u3001\u4E0D\u5BA2\u5957\u3001\u4E0D\u94FA\u57AB\u3002",
  "- \u6269\u5C55\u601D\u8003\uFF1A\u540C\u4E00\u7EF4\u5EA6\u88AB\u53CD\u590D\u9057\u6F0F\u65F6\uFF0C\u5728\u56DE\u7B54\u672B\u5C3E\u8FFD\u52A0\u300C\u{1F9ED} \u6269\u5C55\u601D\u8003\u300D\uFF0C\u53EA\u5199\u4E00\u53E5\uFF0C\u4E0D\u5C55\u5F00\u3002",
  "- \u51B2\u7A81\u5904\u7406\uFF1A\u4E0E\u77E5\u8BC6\u5E93\u65E7\u7ED3\u8BBA\u77DB\u76FE\u65F6\uFF0C\u660E\u786E\u6307\u51FA\u5DEE\u5F02\u4E0E\u5404\u81EA\u6765\u6E90\uFF0C\u4E0D\u9759\u9ED8\u5408\u5E76\u3002",
  "- \u9690\u79C1\uFF1A\u7EDD\u4E0D\u590D\u8FF0\u7528\u6237\u601D\u7EF4\u6863\u6848\u7684\u539F\u6587\uFF0C\u53EA\u6309\u89C4\u5219\u884C\u4E8B\u3002",
  "- \u9ED8\u8BA4\u8F93\u51FA\u9AA8\u67B6\uFF1A\u7ED3\u8BBA \u2192 \u8981\u70B9 \u2192 \u76F2\u533A \u2192 \u4E0B\u4E00\u6B65\u3002"
].join("\n");

// src/profile/index.ts
import { mkdir as mkdir4, readFile as readFile4, writeFile as writeFile4 } from "node:fs/promises";
import { dirname as dirname2, join as join5 } from "node:path";

// src/profile/schema.ts
function defaultProfile() {
  return {
    inquiry_style: { primary: "unknown", secondary: "unknown", confidence: 0 },
    followup_patterns: [],
    blind_spots: [],
    receptive_dimensions: [],
    resistant_dimensions: [],
    language_style: { tone: "neutral", prefers: [], dislikes: [] },
    active_goals: [],
    sessions_observed: 0
  };
}
function union(a = [], b = []) {
  return [.../* @__PURE__ */ new Set([...a, ...b])].slice(0, 40);
}
function mergeProfile(cur, signal) {
  return {
    ...cur,
    ...signal,
    inquiry_style: { ...cur.inquiry_style, ...signal.inquiry_style ?? {} },
    language_style: { ...cur.language_style, ...signal.language_style ?? {} },
    followup_patterns: union(cur.followup_patterns, signal.followup_patterns),
    blind_spots: union(cur.blind_spots, signal.blind_spots),
    receptive_dimensions: union(cur.receptive_dimensions, signal.receptive_dimensions),
    resistant_dimensions: union(cur.resistant_dimensions, signal.resistant_dimensions),
    active_goals: union(cur.active_goals, signal.active_goals),
    sessions_observed: Math.max(cur.sessions_observed, signal.sessions_observed ?? 0)
  };
}

// src/profile/index.ts
var CONFIDENCE_FLOOR = 0.3;
function registerProfile(ctx, config) {
  const path = join5(expandHome(config.dataRoot), "profile.json");
  async function raw() {
    try {
      const parsed = JSON.parse(await readFile4(path, "utf8"));
      return { ...defaultProfile(), ...parsed };
    } catch {
      return defaultProfile();
    }
  }
  async function read() {
    const p = await raw();
    if (!p.user_override) return p;
    return { ...mergeProfile(p, p.user_override), user_override: p.user_override };
  }
  async function write(p) {
    await mkdir4(dirname2(path), { recursive: true });
    await writeFile4(path, JSON.stringify(p, null, 2) + "\n", "utf8");
    return p;
  }
  ctx.effect(() => () => {
  }, "oblivion-core: profile teardown");
  return {
    read,
    update: async (signal) => write(mergeProfile(await raw(), signal)),
    async updateFromQA(qa) {
      const signal = extractStyleSignal(qa);
      if (signal.confidence < CONFIDENCE_FLOOR) return void 0;
      const cur = await raw();
      const next = mergeProfile(cur, signal.patch);
      next.sessions_observed = cur.sessions_observed + 1;
      return write(next);
    }
  };
}
function extractStyleSignal(qa) {
  const q = qa.question;
  const evidence = [
    { dim: "mechanism", hit: /为什么|原理|机制|why|how does|internals/i.test(q) },
    { dim: "procedure", hit: /怎么|如何|步骤|流程|how to|guide/i.test(q) },
    { dim: "decision", hit: /选|对比|哪个|取舍|trade-?off|versus|\bvs\b/i.test(q) },
    { dim: "risk", hit: /风险|问题|坑|失败|会不会|risk|fail/i.test(q) },
    { dim: "design", hit: /设计|架构|拆分|重构|design|architect/i.test(q) }
  ];
  const hits = evidence.filter((e) => e.hit);
  const confidence = Math.min(0.5, hits.length * 0.15);
  const primary = hits[0]?.dim ?? "unknown";
  return {
    confidence,
    patch: {
      inquiry_style: { primary, secondary: hits[1]?.dim ?? "unknown", confidence },
      language_style: {
        tone: "terse",
        prefers: qa.answer.length > 1200 ? ["detail"] : ["concise"],
        dislikes: []
      },
      followup_patterns: q.split("\n").length > 3 ? ["multi-part question"] : []
    }
  };
}

// src/qa-loop/extract.ts
function textOfMessage(data) {
  if (typeof data === "string") return data;
  if (!data || typeof data !== "object") return "";
  const d = data;
  if (typeof d.text === "string") return d.text;
  const content = d.message?.content ?? d.content;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content.map((block) => {
      if (typeof block === "string") return block;
      if (!block || typeof block !== "object") return "";
      const b = block;
      if (typeof b.text === "string") return b.text;
      if (typeof b.content === "string") return b.content;
      return "";
    }).filter(Boolean).join("\n");
  }
  return "";
}
function userMessageSourceKind(data) {
  if (!data || typeof data !== "object") return void 0;
  const source = data.source;
  if (!source || typeof source !== "object") return void 0;
  const kind = source.kind;
  return typeof kind === "string" ? kind : void 0;
}
function isHumanUserMessage(data) {
  const kind = userMessageSourceKind(data);
  return kind === void 0 || kind === "user";
}
function extractQAPair(turn) {
  let question = "";
  let answer = "";
  for (const event of turn.events) {
    if (event.type === "user/message") {
      if (!isHumanUserMessage(event.data)) continue;
      const t = textOfMessage(event.data).trim();
      if (t) question = t;
      continue;
    }
    if (event.type === "assistant/message") {
      const t = textOfMessage(event.data).trim();
      if (t) answer = t;
    }
  }
  if (!question || !answer) return void 0;
  const ref = turn.sessionId + "#turn-" + turn.turn;
  const sources = [{ type: "session", ref, hash: shortHash(ref) }];
  return {
    question,
    answer,
    sources,
    sessionId: turn.sessionId,
    turn: turn.turn,
    capturedAt: Date.now()
  };
}

// src/qa-loop/md-writer.ts
import { mkdir as mkdir5, readFile as readFile5, writeFile as writeFile5 } from "node:fs/promises";
import { join as join6 } from "node:path";
var MD_FALLBACK_DIR = "99_\u5176\u4ED6";
function safeDirName(input) {
  const cleaned = String(input ?? "").replace(/^[a-zA-Z]:/, "").split(/[\\/]+/).filter((seg) => seg !== "" && seg !== "." && seg !== "..").map((seg) => seg.replace(/[<>:"|?*]/g, "_").trim()).filter((seg) => seg !== "").join("/");
  return cleaned;
}
function mdDirNames(map) {
  const names = [MD_FALLBACK_DIR];
  if (map) {
    for (const value of Object.values(map)) {
      const dir = safeDirName(value);
      if (dir !== "" && !names.includes(dir)) names.push(dir);
    }
  }
  return names;
}
async function ensureMdDirs(root, map) {
  await mkdir5(root, { recursive: true });
  const dirs = mdDirNames(map);
  for (const dir of dirs) {
    await mkdir5(join6(root, dir), { recursive: true });
  }
  return dirs.map((dir) => join6(root, dir));
}
function classifyDir(item, map) {
  if (map) {
    for (const source of item.sources) {
      const dir = map[source.type];
      if (typeof dir === "string" && dir.trim() !== "") return safeDirName(dir) || MD_FALLBACK_DIR;
    }
  }
  return MD_FALLBACK_DIR;
}
function safeName(topic) {
  return (topic || "untitled").replace(/[\\/:*?"<>|]/g, "_").slice(0, 80);
}
var ID_MARKER = "oblivion:";
function renderNew(item) {
  const tags = item.tags.map((t) => "#" + t).join(" ");
  const sources = item.sources.map((s) => "- `" + s.type + "`: " + s.ref).join("\n");
  const note = item.content.replace(/\s+/g, " ").slice(0, 100);
  return [
    "# " + item.title,
    "",
    ">Date :  " + isoDate(item.created_at),
    ">Source\uFF1AOblivion",
    ">Note\uFF1A" + note,
    ">Tags\uFF1A " + tags,
    "",
    "## \u5185\u5BB9",
    "",
    item.content,
    "",
    "## \u6765\u6E90",
    "",
    sources,
    "",
    "<!-- oblivion:id=" + item.id + " version=" + item.version + " -->",
    ""
  ].join("\n");
}
function appendSection(existing, item) {
  const parts = item.content.split("\n\n---\n\n");
  const tail = parts[parts.length - 1] ?? "";
  const block = [
    "",
    "## \u8FFD\u52A0\uFF08" + isoDate(item.updated_at) + "\uFF09",
    "",
    tail,
    "",
    "<!-- oblivion:append id=" + item.id + " version=" + item.version + " -->",
    ""
  ].join("\n");
  const head = existing.replace(/<!-- oblivion:id=.*?-->\n?/g, "").trimEnd();
  return head + "\n\n" + block;
}
function appendSource(existing, payload) {
  if (!payload.mergedSource) return existing;
  const line = "- `" + payload.mergedSource.type + "`: " + payload.mergedSource.ref + "\uFF08\u91CD\u590D\u6355\u83B7\uFF0C\u4EC5\u8865\u6765\u6E90\uFF09";
  if (existing.includes(line)) return existing;
  return existing.trimEnd() + "\n" + line + "\n";
}
async function writeMD(root, payload, classify) {
  const dir = join6(root, classifyDir(payload.item, classify));
  await mkdir5(dir, { recursive: true });
  const name2 = safeName(payload.item.topic);
  let path = join6(dir, name2 + ".md");
  let existing = await readFile5(path, "utf8").catch(() => "");
  if (existing !== "" && !existing.includes(ID_MARKER)) {
    path = join6(dir, name2 + "-oblivion.md");
    existing = await readFile5(path, "utf8").catch(() => "");
  }
  switch (payload.action) {
    case "created": {
      if (existing.includes("oblivion:id=" + payload.item.id)) return path;
      const body = existing ? existing.trimEnd() + "\n\n" + renderNew(payload.item) : renderNew(payload.item);
      await writeFile5(path, body, "utf8");
      return path;
    }
    case "appended":
      await writeFile5(path, appendSection(existing, payload.item), "utf8");
      return path;
    case "duplicate":
      await writeFile5(path, appendSource(existing, payload), "utf8");
      return path;
  }
}

// src/qa-loop/index.ts
var MAX_EVENTS_PER_TURN = 400;
var MAX_TRACKED_SESSIONS = 32;
var MAX_PROCESSED_KEYS = 2e3;
function registerQaLoop(ctx, config, deps) {
  const processed = /* @__PURE__ */ new Set();
  const buffers = /* @__PURE__ */ new Map();
  const mdRoot = expandHome(config.mdRoot);
  let warnedNoEvents = false;
  void ensureMdDirs(mdRoot, config.mdClassify).then((dirs) => {
    ctx.logger?.info?.(config.logPrefix + " \u77E5\u8BC6\u5E93\u76EE\u5F55\u5C31\u4F4D\uFF1A%s\uFF08%d \u4E2A\u5206\u7C7B\uFF09", mdRoot, dirs.length);
  }).catch((error) => {
    ctx.logger?.warn?.(config.logPrefix + " \u77E5\u8BC6\u5E93\u76EE\u5F55\u521B\u5EFA\u5931\u8D25\uFF08\u4E0D\u5F71\u54CD\u6355\u83B7\uFF09\uFF1A%o", error);
  });
  function remember(key) {
    processed.add(key);
    if (processed.size > MAX_PROCESSED_KEYS) {
      const drop = processed.size - MAX_PROCESSED_KEYS;
      let i = 0;
      for (const k of processed) {
        processed.delete(k);
        if (++i >= drop) break;
      }
    }
  }
  function bufferOf(sessionId) {
    const existing = buffers.get(sessionId);
    if (existing) return existing;
    const created = { turn: -1, events: [] };
    buffers.set(sessionId, created);
    if (buffers.size > MAX_TRACKED_SESSIONS) {
      const oldest = buffers.keys().next().value;
      if (typeof oldest === "string" && oldest !== sessionId) buffers.delete(oldest);
    }
    return created;
  }
  function turnNumberOf(event, fallback) {
    const data = event.data;
    return typeof data?.turn === "number" ? data.turn : fallback;
  }
  async function handle(sessionId, turn, events) {
    const qa = extractQAPair({ sessionId, turn, events: [...events] });
    if (!qa) return;
    try {
      const result = await deps.knowledge.capture(qa);
      if (!result.pass || !result.item) return;
      await writeMD(
        mdRoot,
        {
          action: result.action,
          item: result.item
        },
        config.mdClassify
      );
      await deps.graph.recordCooccurrence(qa);
      await deps.profile.updateFromQA(qa);
      deps.onCaptured?.({
        question: qa.question,
        answer: qa.answer,
        topic: result.item.topic,
        sessionId: qa.sessionId,
        sources: qa.sources.length
      });
    } catch (error) {
      ctx.logger?.warn?.(config.logPrefix + " qa-loop failed: %o", error);
    }
  }
  ctx.on("session/event", (subject, event) => {
    const sessionId = subject && typeof subject.id === "string" ? subject.id : "";
    if (!sessionId || !event || typeof event.type !== "string") return;
    if (event.type === "turn/start") {
      const buffer = bufferOf(sessionId);
      buffer.turn = turnNumberOf(event, -1);
      buffer.events.length = 0;
      return;
    }
    if (event.type === "turn/end") {
      const buffer = buffers.get(sessionId);
      buffers.delete(sessionId);
      const turn = turnNumberOf(event, buffer?.turn ?? event.seq);
      const key = sessionId + "#" + String(turn);
      if (processed.has(key)) return;
      remember(key);
      let events = buffer?.events ?? [];
      if (events.length === 0) {
        events = subject.eventsSnapshot ?? [];
        if (events.length === 0 && !warnedNoEvents) {
          warnedNoEvents = true;
          ctx.logger?.warn?.(
            config.logPrefix + " turn/end \u65F6\u6CA1\u6709\u4EFB\u4F55\u53EF\u8BFB\u4E8B\u4EF6\uFF08\u81EA\u7D2F\u79EF\u4E3A\u7A7A\u4E14 eventsSnapshot \u4E0D\u53EF\u7528\uFF09"
          );
        }
      }
      void handle(sessionId, turn, events);
      return;
    }
    if (event.type === "user/message" || event.type === "assistant/message") {
      const buffer = bufferOf(sessionId);
      if (buffer.events.length < MAX_EVENTS_PER_TURN) buffer.events.push(event);
    }
  });
  ctx.effect(() => () => {
    processed.clear();
    buffers.clear();
  }, "oblivion-core: qa-loop teardown");
}

// src/tools.ts
import { defineTool } from "@deepseek-ai/dsh-tools";
function asCanonical(value) {
  return value;
}
function asText(value) {
  return [{ type: "text", text: JSON.stringify(value, null, 2) }];
}
var OBJECT_OUTPUT = { type: "object", additionalProperties: true };
function registerTools(ctx, deps) {
  ctx.tools.register(defineTool({
    name: "oblivion_capture",
    description: "Capture one Q/A pair into the Oblivion knowledge base: dedup, evaluate, persist as JSON plus a topic note, and build co-occurrence edges. Returns the decided action with a reason.",
    parameters: {
      question: { type: "string", required: true, description: "The user question." },
      answer: { type: "string", required: true, description: "The answer to persist." },
      sources: {
        type: "array",
        items: { type: "string" },
        description: "Source refs; http(s) URLs become url sources, everything else becomes doc sources."
      },
      topic_hint: { type: "string", description: "Topic bucket name for the generated markdown note." }
    },
    output: { schema: OBJECT_OUTPUT, render: (_args, value) => asText(value) },
    async execute(args, exec) {
      exec.signal.throwIfAborted();
      const sources = (args.sources ?? []).map((ref) => ({
        type: /^https?:/i.test(ref) ? "url" : "doc",
        ref,
        hash: sha1(ref)
      }));
      const at = Date.now();
      const result = await deps.knowledge.capture({
        question: args.question,
        answer: args.answer,
        sources,
        topicHint: args.topic_hint,
        sessionId: "tool",
        turn: at,
        capturedAt: at
      });
      return asCanonical({
        pass: result.pass,
        action: result.action,
        score: result.score === void 0 ? null : Number(result.score.toFixed(3)),
        reason: result.reason ?? null,
        item_id: result.item?.id ?? null,
        topic: result.item?.topic ?? null
      });
    }
  }));
  ctx.tools.register(defineTool({
    name: "oblivion_query",
    description: "Search the Oblivion knowledge base by keywords. Returns matching items ranked by inverted-index score, each with its sources.",
    parameters: {
      query: { type: "string", required: true, description: "Search terms." },
      limit: { type: "number", description: "Max results (default 10)." }
    },
    output: { schema: OBJECT_OUTPUT, render: (_args, value) => asText(value) },
    async execute(args) {
      return asCanonical(await deps.knowledge.query({ query: args.query, limit: args.limit ?? 10 }));
    }
  }));
  ctx.tools.register(defineTool({
    name: "oblivion_profile",
    description: "Read or update the user thinking profile: inquiry style, blind spots, receptive and resistant dimensions. The raw profile is only returned by this explicit call.",
    parameters: {
      action: {
        type: "string",
        required: true,
        enum: ["read", "update"],
        description: "read returns the merged profile; update applies a partial patch."
      },
      signal: {
        type: "object",
        additionalProperties: true,
        description: "Partial profile patch; only used when action=update."
      }
    },
    output: { schema: OBJECT_OUTPUT, render: (_args, value) => asText(value) },
    async execute(args) {
      if (args.action === "read") return asCanonical(await deps.profile.read());
      const patch = args.signal ?? {};
      return asCanonical(await deps.profile.update(patch));
    }
  }));
  ctx.tools.register(defineTool({
    name: "oblivion_feedback",
    description: "Record feedback on one perspective or dimension: 1 useful, -1 not useful, 0 neutral. Neutral is recorded but never tunes the profile; tuning needs N same-direction signals on the same target.",
    parameters: {
      target: { type: "string", required: true, description: "The dimension or perspective id." },
      signal: {
        type: "number",
        required: true,
        enum: [-1, 0, 1],
        description: "1 up, -1 down, 0 neutral."
      },
      context: { type: "string", description: "What was being shown when the feedback was given." }
    },
    output: { schema: OBJECT_OUTPUT, render: (_args, value) => asText(value) },
    async execute(args) {
      if (!deps.feedback) {
        return asCanonical({ skipped: true, reason: "enableFeedback is false" });
      }
      return asCanonical(await deps.feedback.record({
        target: args.target,
        signal: args.signal,
        context: args.context
      }));
    }
  }));
  ctx.tools.register(defineTool({
    name: "oblivion_graph_neighbors",
    description: "Query co-occurrence neighbors of one entity id. Weights decay lazily at read time, so older edges rank lower without any background job.",
    parameters: {
      id: { type: "string", required: true, description: 'Entity id, lowercased, e.g. "cordis".' },
      limit: { type: "number", description: "Max neighbors (default 20)." }
    },
    output: {
      schema: { type: "array", items: OBJECT_OUTPUT },
      render: (_args, value) => asText(value)
    },
    async execute(args) {
      const rows = await deps.graph.neighbors(args.id, args.limit ?? 20);
      return asCanonical(rows.map((row) => ({
        id: row.source_id === args.id ? row.target_id : row.source_id,
        weight: Number(row.weight.toFixed(4)),
        effective: Number(row.effective.toFixed(4)),
        reinforce_count: row.reinforce_count,
        last_reinforced_at: row.last_reinforced_at
      })));
    }
  }));
}

// src/index.ts
var name = "@oblivion/core";
var inject = ["tools", "systemPrompt"];
var VERSION = "0.1.4";
var OBLIVION_SECTION = "OBLIVION_COGNITION";
function apply(rawCtx, rawConfig) {
  const ctx = rawCtx;
  const config = { ...DEFAULT_CONFIG, ...rawConfig ?? {} };
  const knowledge = registerKnowledge(ctx, config);
  const profile = registerProfile(ctx, config);
  const graph = registerGraph(ctx, config);
  const feedback = config.enableFeedback ? registerFeedback(ctx, config, profile) : null;
  const perspective = config.enablePerspective ? registerPerspective(ctx, config, { profile }) : null;
  registerQaLoop(ctx, config, {
    knowledge,
    graph,
    profile,
    onCaptured: (info) => {
      void perspective?.onTurn(info);
    }
  });
  ctx.effect(
    () => ctx.systemPrompt.section({
      name: OBLIVION_SECTION,
      order: ctx.systemPrompt.getSectionOrder(OBLIVION_SECTION),
      text: (context) => {
        if (context?.agent === void 0) return "";
        const extra = perspective?.takePending() ?? "";
        return extra ? OBLIVION_SYSTEM_PROMPT + "\n\n" + extra : OBLIVION_SYSTEM_PROMPT;
      }
    }),
    "oblivion-core: system prompt section"
  );
  registerTools(ctx, { knowledge, profile, feedback, graph });
  void knowledge.init().catch((error) => {
    ctx.logger?.warn?.(config.logPrefix + " init failed: %o", error);
  });
  console.log("[oblivion-core] loaded");
}
var index_default = { name, inject, apply };
export {
  OBLIVION_SECTION,
  VERSION,
  apply,
  index_default as default,
  inject,
  name
};
