// GENERATED by scripts/build.mjs -- do not edit by hand.

// src/knowledge/search.ts
var STOP = /* @__PURE__ */ new Set([
  "the",
  "and",
  "for",
  "with",
  "that",
  "this",
  "from",
  "are",
  "was",
  "were",
  "\u4F60",
  "\u6211",
  "\u4ED6",
  "\u5979",
  "\u7684",
  "\u4E86",
  "\u662F",
  "\u5728",
  "\u548C",
  "\u5C31",
  "\u90FD",
  "\u800C",
  "\u53CA",
  "\u4E0E",
  "\u6216",
  "\u4E00\u4E2A",
  "\u8FD9\u4E2A",
  "\u90A3\u4E2A",
  "\u4EC0\u4E48",
  "\u600E\u4E48",
  "\u5982\u4F55",
  "\u53EF\u4EE5",
  "\u9700\u8981"
]);
function tokenize(text) {
  const out = [];
  for (const chunk of text.toLowerCase().split(/[^\p{L}\p{N}]+/u)) {
    if (!chunk) continue;
    if (/[\u3040-\u30ff\u3400-\u9fff]/.test(chunk)) {
      for (const ch of chunk) if (!STOP.has(ch)) out.push(ch);
      if (chunk.length >= 2) out.push(chunk);
      continue;
    }
    if (chunk.length >= 2 && !STOP.has(chunk)) out.push(chunk);
  }
  return out;
}
function jaccard(a, b) {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const t of a) if (b.has(t)) inter += 1;
  return inter / (a.size + b.size - inter);
}

// src/knowledge/evaluate.ts
function heuristicScore(qa) {
  const answer = qa.answer;
  const lengthScore = Math.min(1, answer.length / 800);
  const richnessScore = Math.min(1, new Set(tokenize(answer)).size / 160);
  const sourceScore = Math.min(1, qa.sources.length / 2);
  const hasCode = /```|\b(function|class|const|let|SELECT|FROM|npm|pnpm|dshx|docker)\b/i.test(answer) ? 1 : 0;
  const hasNumber = /\d/.test(answer) ? 1 : 0;
  const hasStructure = /(^|\n)\s*(#{2,4}\s|[-*]\s|\d+[.)]\s|\|)/.test(answer) ? 1 : 0;
  const hasTopic = qa.topicHint ? 1 : 0;
  return lengthScore * 0.25 + richnessScore * 0.2 + sourceScore * 0.2 + hasCode * 0.1 + hasNumber * 0.1 + hasStructure * 0.05 + hasTopic * 0.1;
}
async function evaluate(qa, ctx = {}) {
  const base = heuristicScore(qa);
  if (!ctx.llmScore) return base;
  const llm = await ctx.llmScore(qa).catch(() => void 0);
  if (typeof llm !== "number" || Number.isNaN(llm)) return base;
  return Math.min(1, Math.max(0, Math.min(1, Math.max(0, llm)) * 0.7 + base * 0.3));
}

// src/knowledge/filter.ts
function isOblivionOriginated(qa) {
  return qa.sources.some((s) => s.type === "qa_loop" || s.ref.startsWith("oblivion:"));
}
function passesRules(qa, config) {
  if (isOblivionOriginated(qa)) return { pass: false, reason: "oblivion-originated" };
  if (qa.sources.length === 0) return { pass: false, reason: "no-source" };
  return checkL3Rules(qa, config);
}
var MEANINGLESS_TOKENS = /* @__PURE__ */ new Set([
  "\u65E0",
  "\u6CA1\u6709",
  "\u6682\u65E0",
  "\u4E0D\u77E5\u9053",
  "\u4E0D\u6E05\u695A",
  "\u6D4B\u8BD5",
  "\u8BD5\u8BD5",
  "\u5360\u4F4D",
  "\u7565",
  "\u540C\u4E0A",
  "test",
  "testing",
  "asdf",
  "qwer",
  "aaa",
  "zzz",
  "todo",
  "tbd",
  "na",
  "n/a"
]);
var PLEASANTRY_TOKENS = /(?:辛苦了|太感谢|感谢你|谢谢你|多谢|谢谢|感谢|好的|好嘞|行吧|可以|收到|明白|了解|懂了|辛苦了|thanks|thank you|thx|okay|ok|got it|nice|cool|嗯+|哦+|啊+|哈哈+|呵呵)/gi;
var FILLER_TOKENS = /(?:你|您|啦|了|的|呀|啊|哦|咯|喽|哈|吧|呢|嘛|~)/g;
var PLEASANTRY_MAX_CHARS = 24;
function isPleasantryOnly(answer) {
  const trimmed = answer.trim();
  if (trimmed === "" || trimmed.length > PLEASANTRY_MAX_CHARS) return false;
  const stripped = trimmed.replace(/[\s\p{P}\p{S}]/gu, "");
  if (stripped === "") return false;
  const leftover = stripped.replace(PLEASANTRY_TOKENS, "").replace(FILLER_TOKENS, "");
  return leftover === "";
}
var UNKNOWN_ANSWER = /^\s*(?:我|我们)?\s*(?:也)?\s*(?:不知道|不清楚|不了解|不确定|无法确定|无从得知|不会|i\s*don'?t\s*know|not\s*sure|no\s*idea)/i;
var UNKNOWN_HEAD_CHARS = 40;
function isMeaninglessOnly(answer) {
  const withoutPunctuation = answer.replace(/[\s\p{P}\p{S}]/gu, " ").trim();
  if (withoutPunctuation === "") return true;
  const tokens = withoutPunctuation.split(/\s+/).filter((t) => t.length > 0);
  if (tokens.length === 0) return true;
  return tokens.every((t) => t.length <= 1 || MEANINGLESS_TOKENS.has(t.toLowerCase()));
}
function checkL3Rules(qa, config) {
  const answer = qa.answer.trim();
  if (answer.length < config.minAnswerLength) return { pass: false, reason: "answer-too-short" };
  if (isMeaninglessOnly(answer)) return { pass: false, reason: "meaningless-only" };
  if (UNKNOWN_ANSWER.test(answer.slice(0, UNKNOWN_HEAD_CHARS))) return { pass: false, reason: "contains-unknown" };
  if (isPleasantryOnly(answer)) return { pass: false, reason: "pleasantry-only" };
  return { pass: true };
}
async function fourLayerFilter(qa, config, deps) {
  if (await deps.exactDuplicate(qa)) {
    return { pass: false, action: "duplicate", reason: "exact hash match" };
  }
  const sim = await deps.semanticSimilar(qa, config.semanticThreshold);
  if (sim.action === "duplicate") {
    return { pass: false, action: "duplicate", reason: "semantic duplicate", existing: sim.existing };
  }
  if (sim.action === "conflict") {
    return { pass: false, action: "conflict", reason: "conflicts with existing item", existing: sim.existing };
  }
  const rules = passesRules(qa, config);
  if (!rules.pass) {
    return { pass: false, action: "ignored", reason: rules.reason };
  }
  const score = await evaluate(qa, deps.evaluateContext);
  if (score < config.valueThreshold) {
    return { pass: false, action: "ignored", score, reason: "below value threshold" };
  }
  return {
    pass: true,
    action: sim.action === "appended" ? "appended" : "created",
    score,
    existing: sim.existing
  };
}
function compareByOverlap(qa, candidates, threshold) {
  const qaTokens = new Set(tokenize(qa.question + "\n" + qa.answer));
  let best;
  for (const item of candidates) {
    const ratio2 = jaccard(qaTokens, new Set(tokenize(item.title + "\n" + item.content)));
    if (!best || ratio2 > best.ratio) best = { item, ratio: ratio2 };
  }
  if (!best || best.ratio <= 0) return { action: "new" };
  if (best.ratio >= threshold) {
    const contradicts = flipSignals(qa.answer) !== flipSignals(best.item.content) && best.ratio > 0.7;
    return contradicts ? { action: "conflict", existing: best.item, ratio: best.ratio } : { action: "duplicate", existing: best.item, ratio: best.ratio };
  }
  if (best.ratio >= threshold * 0.6 && qa.answer.length > best.item.content.length) {
    return { action: "appended", existing: best.item, ratio: best.ratio };
  }
  return { action: "new", ratio: best.ratio };
}
function flipSignals(text) {
  const negations = (text.match(/不|没有|无法|禁止|不能|cannot|not\b|never|no longer/gi) ?? []).length;
  return negations % 2 === 0 ? "affirm" : "negate";
}

// src/util/time.ts
var MS_PER_DAY = 864e5;
function now() {
  return Date.now();
}
function ageDays(from, at = now()) {
  return Math.max(0, (at - from) / MS_PER_DAY);
}
function newId(at = now()) {
  const rand = Math.random().toString(36).slice(2, 4).padEnd(2, "0");
  return `ts-${at.toString(36)}-${rand}`;
}
function isoDate(at) {
  return new Date(at).toISOString().slice(0, 10);
}

// src/graph/decay.ts
function effectiveWeight(edge, cfg, at = now()) {
  const age = ageDays(edge.last_reinforced_at, at);
  const decayed = edge.weight * Math.pow(cfg.base, age / Math.max(1, cfg.periodDays));
  return Math.min(edge.weight, Math.max(0, decayed));
}
function reinforce(edge, cfg, at = now()) {
  return {
    ...edge,
    weight: Math.min(cfg.cap, edge.weight + cfg.delta),
    last_reinforced_at: at,
    reinforce_count: edge.reinforce_count + 1
  };
}

// src/util/paths.ts
import { homedir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";
function expandHome(p) {
  const home = homedir();
  if (!p) return home;
  if (p === "~") return home;
  if (p.startsWith("~/") || p.startsWith("~\\")) return join(home, p.slice(2));
  return isAbsolute(p) ? p : resolve(p);
}

// src/graph/index.ts
function extractEntities(text, cap = 24) {
  const out = /* @__PURE__ */ new Set();
  const re = /[A-Za-z][\w.-]{2,}|[\u4e00-\u9fff]{2,8}/g;
  for (const m of text.matchAll(re)) {
    const t = m[0].toLowerCase();
    if (t.length < 2 || t.length > 32) continue;
    out.add(t);
    if (out.size >= cap) break;
  }
  return [...out];
}

// src/util/hash.ts
import { createHash } from "node:crypto";
function sha1(input) {
  return createHash("sha1").update(input, "utf8").digest("hex");
}
function normalizeForHash(text) {
  return text.toLowerCase().replace(/[\s\u3000]+/g, " ").replace(/[，。、；：！？,.;:!?"'\u201c\u201d\u2018\u2019()（）\[\]【】《》<>`*_\-—]+/g, "").trim();
}
function shortHash(input) {
  return sha1(input).slice(0, 12);
}

// src/qa-loop/extract.ts
function textOfMessage(data) {
  if (typeof data === "string") return data;
  if (!data || typeof data !== "object") return "";
  const d = data;
  if (typeof d.text === "string") return d.text;
  const content = d.message?.content ?? d.content;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content.map((block) => {
      if (typeof block === "string") return block;
      if (!block || typeof block !== "object") return "";
      const b = block;
      if (typeof b.text === "string") return b.text;
      if (typeof b.content === "string") return b.content;
      return "";
    }).filter(Boolean).join("\n");
  }
  return "";
}
function userMessageSourceKind(data) {
  if (!data || typeof data !== "object") return void 0;
  const source = data.source;
  if (!source || typeof source !== "object") return void 0;
  const kind = source.kind;
  return typeof kind === "string" ? kind : void 0;
}
function isHumanUserMessage(data) {
  const kind = userMessageSourceKind(data);
  return kind === void 0 || kind === "user";
}
function extractQAPair(turn) {
  let question = "";
  let answer = "";
  for (const event of turn.events) {
    if (event.type === "user/message") {
      if (!isHumanUserMessage(event.data)) continue;
      const t = textOfMessage(event.data).trim();
      if (t) question = t;
      continue;
    }
    if (event.type === "assistant/message") {
      const t = textOfMessage(event.data).trim();
      if (t) answer = t;
    }
  }
  if (!question || !answer) return void 0;
  const ref = turn.sessionId + "#turn-" + turn.turn;
  const sources = [{ type: "session", ref, hash: shortHash(ref) }];
  return {
    question,
    answer,
    sources,
    sessionId: turn.sessionId,
    turn: turn.turn,
    capturedAt: Date.now()
  };
}

// src/qa-loop/index.ts
import { appendFile, mkdir as mkdir2, readFile as readFile2, writeFile as writeFile2 } from "node:fs/promises";
import { dirname, join as join3 } from "node:path";

// src/qa-loop/md-writer.ts
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join as join2 } from "node:path";
var MD_FALLBACK_DIR = "99_\u5176\u4ED6";
function safeDirName(input) {
  const cleaned = String(input ?? "").replace(/^[a-zA-Z]:/, "").split(/[\\/]+/).filter((seg) => seg !== "" && seg !== "." && seg !== "..").map((seg) => seg.replace(/[<>:"|?*]/g, "_").trim()).filter((seg) => seg !== "").join("/");
  return cleaned;
}
function mdDirNames(map) {
  const names = [MD_FALLBACK_DIR];
  if (map) {
    for (const value of Object.values(map)) {
      const dir = safeDirName(value);
      if (dir !== "" && !names.includes(dir)) names.push(dir);
    }
  }
  return names;
}
async function ensureMdDirs(root, map) {
  await mkdir(root, { recursive: true });
  const dirs = mdDirNames(map);
  for (const dir of dirs) {
    await mkdir(join2(root, dir), { recursive: true });
  }
  return dirs.map((dir) => join2(root, dir));
}
function classifyDir(item, map) {
  if (map) {
    for (const source of item.sources) {
      const dir = map[source.type];
      if (typeof dir === "string" && dir.trim() !== "") return safeDirName(dir) || MD_FALLBACK_DIR;
    }
  }
  return MD_FALLBACK_DIR;
}
function safeName(topic) {
  return (topic || "untitled").replace(/[\\/:*?"<>|]/g, "_").slice(0, 80);
}
var ID_MARKER = "oblivion:";
function renderNew(item) {
  const tags = item.tags.map((t) => "#" + t).join(" ");
  const sources = item.sources.map((s) => "- `" + s.type + "`: " + s.ref).join("\n");
  const note = item.content.replace(/\s+/g, " ").slice(0, 100);
  return [
    "# " + item.title,
    "",
    ">Date :  " + isoDate(item.created_at),
    ">Source\uFF1AOblivion",
    ">Note\uFF1A" + note,
    ">Tags\uFF1A " + tags,
    "",
    "## \u5185\u5BB9",
    "",
    item.content,
    "",
    "## \u6765\u6E90",
    "",
    sources,
    "",
    "<!-- oblivion:id=" + item.id + " version=" + item.version + " -->",
    ""
  ].join("\n");
}
function appendSection(existing, item) {
  const parts = item.content.split("\n\n---\n\n");
  const tail = parts[parts.length - 1] ?? "";
  const block = [
    "",
    "## \u8FFD\u52A0\uFF08" + isoDate(item.updated_at) + "\uFF09",
    "",
    tail,
    "",
    "<!-- oblivion:append id=" + item.id + " version=" + item.version + " -->",
    ""
  ].join("\n");
  const head = existing.replace(/<!-- oblivion:id=.*?-->\n?/g, "").trimEnd();
  return head + "\n\n" + block;
}
function appendSource(existing, payload) {
  if (!payload.mergedSource) return existing;
  const line = "- `" + payload.mergedSource.type + "`: " + payload.mergedSource.ref + "\uFF08\u91CD\u590D\u6355\u83B7\uFF0C\u4EC5\u8865\u6765\u6E90\uFF09";
  if (existing.includes(line)) return existing;
  return existing.trimEnd() + "\n" + line + "\n";
}
async function writeMD(root, payload, classify) {
  const dir = join2(root, classifyDir(payload.item, classify));
  await mkdir(dir, { recursive: true });
  const name = safeName(payload.item.topic);
  let path = join2(dir, name + ".md");
  let existing = await readFile(path, "utf8").catch(() => "");
  if (existing !== "" && !existing.includes(ID_MARKER)) {
    path = join2(dir, name + "-oblivion.md");
    existing = await readFile(path, "utf8").catch(() => "");
  }
  switch (payload.action) {
    case "created": {
      if (existing.includes("oblivion:id=" + payload.item.id)) return path;
      const body = existing ? existing.trimEnd() + "\n\n" + renderNew(payload.item) : renderNew(payload.item);
      await writeFile(path, body, "utf8");
      return path;
    }
    case "appended":
      await writeFile(path, appendSection(existing, payload.item), "utf8");
      return path;
    case "duplicate":
      await writeFile(path, appendSource(existing, payload), "utf8");
      return path;
  }
}

// src/qa-loop/index.ts
var MAX_EVENTS_PER_TURN = 400;
var MAX_TRACKED_SESSIONS = 32;
var MAX_PROCESSED_KEYS = 2e3;
function registerQaLoop(ctx, config, deps) {
  const processed = /* @__PURE__ */ new Set();
  const buffers = /* @__PURE__ */ new Map();
  const mdRoot = expandHome(config.mdRoot);
  let warnedNoEvents = false;
  void ensureMdDirs(mdRoot, config.mdClassify).then((dirs) => {
    ctx.logger?.info?.(config.logPrefix + " \u77E5\u8BC6\u5E93\u76EE\u5F55\u5C31\u4F4D\uFF1A%s\uFF08%d \u4E2A\u5206\u7C7B\uFF09", mdRoot, dirs.length);
  }).catch((error) => {
    ctx.logger?.warn?.(config.logPrefix + " \u77E5\u8BC6\u5E93\u76EE\u5F55\u521B\u5EFA\u5931\u8D25\uFF08\u4E0D\u5F71\u54CD\u6355\u83B7\uFF09\uFF1A%o", error);
  });
  function remember(key) {
    processed.add(key);
    if (processed.size > MAX_PROCESSED_KEYS) {
      const drop = processed.size - MAX_PROCESSED_KEYS;
      let i = 0;
      for (const k of processed) {
        processed.delete(k);
        if (++i >= drop) break;
      }
    }
  }
  function bufferOf(sessionId) {
    const existing = buffers.get(sessionId);
    if (existing) return existing;
    const created = { turn: -1, events: [] };
    buffers.set(sessionId, created);
    if (buffers.size > MAX_TRACKED_SESSIONS) {
      const oldest = buffers.keys().next().value;
      if (typeof oldest === "string" && oldest !== sessionId) buffers.delete(oldest);
    }
    return created;
  }
  function turnNumberOf(event, fallback) {
    const data = event.data;
    return typeof data?.turn === "number" ? data.turn : fallback;
  }
  const probePath = join3(expandHome(config.dataRoot), "events-probe.jsonl");
  async function probe(subject, event, sessionId, origin) {
    if (!config.enableEventProbe) return;
    try {
      const data = event?.data;
      const line = JSON.stringify({
        at: Date.now(),
        origin,
        type: event?.type ?? null,
        seq: typeof event?.seq === "number" ? event.seq : null,
        sessionIdOk: sessionId !== "",
        subjectKeys: subject && typeof subject === "object" ? Object.keys(subject).slice(0, 8) : null,
        dataKeys: data && typeof data === "object" ? Object.keys(data).slice(0, 10) : null
      });
      await mkdir2(dirname(probePath), { recursive: true });
      await appendFile(probePath, line + "\n", "utf8");
      const raw = await readFile2(probePath, "utf8");
      const lines = raw.split("\n").filter((l) => l.trim() !== "");
      if (lines.length > config.eventProbeMax) {
        await writeFile2(probePath, lines.slice(-config.eventProbeMax).join("\n") + "\n", "utf8");
      }
    } catch {
    }
  }
  async function trace(entry) {
    if (!deps.stats) return;
    await deps.stats.record({
      at: Date.now(),
      session: entry.sessionId.slice(0, 12),
      turn: entry.turn,
      action: entry.action,
      pass: entry.pass,
      reason: entry.reason,
      score: entry.score,
      questionChars: entry.questionChars ?? 0,
      answerChars: entry.answerChars ?? 0,
      sources: entry.sources ?? 0,
      ms: Math.max(0, Date.now() - entry.startedAt)
    });
  }
  async function handle(sessionId, turn, events) {
    const startedAt = Date.now();
    const qa = extractQAPair({ sessionId, turn, events: [...events] });
    if (!qa) {
      await trace({
        sessionId,
        turn,
        action: "no-qa",
        pass: false,
        reason: "\u672C\u8F6E\u6CA1\u6709\u300C\u771F\u4EBA\u63D0\u95EE + \u56DE\u7B54\u300D\uFF08\u5DE5\u5177\u8F6E/\u6CE8\u5165\u8F6E/\u65E0\u56DE\u7B54\uFF09",
        startedAt
      });
      return;
    }
    try {
      const result = await deps.knowledge.capture(qa);
      await trace({
        sessionId,
        turn,
        action: result.action,
        pass: Boolean(result.pass && result.item),
        reason: result.reason ?? (result.pass ? "captured" : "rejected"),
        score: result.score,
        questionChars: qa.question.length,
        answerChars: qa.answer.length,
        sources: qa.sources.length,
        startedAt
      });
      if (!result.pass || !result.item) return;
      await writeMD(
        mdRoot,
        {
          action: result.action,
          item: result.item
        },
        config.mdClassify
      );
      await deps.graph.recordCooccurrence(qa);
      await deps.profile.updateFromQA(qa);
      deps.onCaptured?.({
        question: qa.question,
        answer: qa.answer,
        topic: result.item.topic,
        sessionId: qa.sessionId,
        sources: qa.sources.length
      });
    } catch (error) {
      ctx.logger?.warn?.(config.logPrefix + " qa-loop failed: %o", error);
      await trace({
        sessionId,
        turn,
        action: "ignored",
        pass: false,
        reason: "exception: " + String(error),
        questionChars: qa.question.length,
        answerChars: qa.answer.length,
        sources: qa.sources.length,
        startedAt
      });
    }
  }
  function onSessionEvent(subject, event, origin) {
    const sessionId = subject && typeof subject.id === "string" ? subject.id : "";
    void probe(subject, event, sessionId, origin);
    if (!sessionId || !event || typeof event.type !== "string") return;
    if (event.type === "turn/start") {
      const buffer = bufferOf(sessionId);
      buffer.turn = turnNumberOf(event, -1);
      buffer.events.length = 0;
      return;
    }
    if (event.type === "turn/end") {
      const buffer = buffers.get(sessionId);
      buffers.delete(sessionId);
      const turn = turnNumberOf(event, buffer?.turn ?? event.seq);
      const key = sessionId + "#" + String(turn);
      if (processed.has(key)) return;
      remember(key);
      let events = buffer?.events ?? [];
      if (events.length === 0) {
        events = subject.eventsSnapshot ?? [];
        if (events.length === 0 && !warnedNoEvents) {
          warnedNoEvents = true;
          ctx.logger?.warn?.(
            config.logPrefix + " turn/end \u65F6\u6CA1\u6709\u4EFB\u4F55\u53EF\u8BFB\u4E8B\u4EF6\uFF08\u81EA\u7D2F\u79EF\u4E3A\u7A7A\u4E14 eventsSnapshot \u4E0D\u53EF\u7528\uFF09"
          );
        }
      }
      void handle(sessionId, turn, events);
      return;
    }
    if (event.type === "user/message" || event.type === "assistant/message") {
      const buffer = bufferOf(sessionId);
      if (buffer.events.length < MAX_EVENTS_PER_TURN) buffer.events.push(event);
    }
  }
  const diagPath = join3(expandHome(config.dataRoot), "mount-diag.json");
  const diag = {
    version: "0.1.9",
    mountedAt: Date.now(),
    hasOn: typeof ctx.on === "function",
    hasInject: typeof ctx.inject === "function",
    hasGet: typeof ctx.get === "function",
    /** 直接读 `ctx.agents`（不经 inject）—— 服务是否已经在这个上下文上 */
    agentsDirect: typeof ctx.agents === "object" && ctx.agents !== null,
    agentsDirectCount: -1,
    /** `ctx.inject(['agents'], …)` 的回调是否触发 */
    injectFired: false,
    injectAgentCount: -1,
    /** 两条订阅各自收到的事件计数 */
    rootSeen: 0,
    agentSeen: 0,
    mountedAgents: 0
  };
  let diagDirty = false;
  async function flushDiag() {
    try {
      await mkdir2(dirname(diagPath), { recursive: true });
      await writeFile2(diagPath, JSON.stringify(diag, null, 2) + "\n", "utf8");
    } catch {
    }
  }
  async function diagOnce() {
    if (!config.enableEventProbe || !diagDirty) return;
    diagDirty = false;
    await flushDiag();
  }
  try {
    const direct = ctx.agents;
    if (direct && typeof direct.list === "function") {
      diag.agentsDirectCount = direct.list().length;
    }
  } catch {
  }
  diagDirty = true;
  void diagOnce();
  const agentDisposers = /* @__PURE__ */ new Map();
  function attachAgent(agent) {
    const agentCtx = agent?.ctx;
    if (!agent || !agentCtx || typeof agentCtx.on !== "function") return;
    if (agentDisposers.has(agent)) return;
    try {
      const dispose = agentCtx.on("session/event", (...inner) => {
        diag.agentSeen += 1;
        diagDirty = true;
        void diagOnce();
        onSessionEvent(inner[0], inner[1], "agent");
      });
      agentDisposers.set(agent, typeof dispose === "function" ? dispose : () => void 0);
      diag.mountedAgents = agentDisposers.size;
      diagDirty = true;
      void diagOnce();
    } catch (error) {
      ctx.logger?.warn?.(config.logPrefix + " agent \u4F5C\u7528\u57DF\u8BA2\u9605\u5931\u8D25\uFF1A%o", error);
    }
  }
  ctx.on("agent/created", (...args) => {
    attachAgent(args[0]?.agent);
  });
  if (typeof ctx.inject === "function") {
    ctx.inject(["agents"], (scope) => {
      diag.injectFired = true;
      const registry = scope.agents;
      const live = registry?.list?.() ?? [];
      diag.injectAgentCount = live.length;
      for (const agent of live) attachAgent(agent);
      diagDirty = true;
      void diagOnce();
      ctx.logger?.info?.(config.logPrefix + " \u5DF2\u7ED9 %d \u4E2A\u5728\u8DD1\u7684 agent \u6302\u4E0A\u4F1A\u8BDD\u4E8B\u4EF6\u8BA2\u9605", live.length);
    });
  }
  ctx.on("session/event", (...args) => {
    diag.rootSeen += 1;
    diagDirty = true;
    void diagOnce();
    onSessionEvent(args[0], args[1], "root");
  });
  ctx.effect(() => () => {
    processed.clear();
    buffers.clear();
    for (const dispose of agentDisposers.values()) {
      try {
        dispose();
      } catch {
      }
    }
    agentDisposers.clear();
  }, "oblivion-core: qa-loop teardown");
}

// src/knowledge/index.ts
function deriveTitle(qa) {
  const q = qa.question.split("\n")[0].trim();
  return q.length > 60 ? q.slice(0, 57) + "\u2026" : q || "untitled";
}
function deriveTopic(qa) {
  if (qa.topicHint) return qa.topicHint;
  const m = qa.question.match(/[\p{L}\p{N}_-]{3,20}/gu);
  return m?.[0] ?? "untitled";
}

// src/feedback/index.ts
import { mkdir as mkdir3, readFile as readFile3, writeFile as writeFile3 } from "node:fs/promises";
import { dirname as dirname2, join as join4 } from "node:path";

// src/feedback/tuner.ts
async function tune(entries, target, profile, threshold) {
  const same = entries.filter((e) => e.target === target && e.signal !== 0);
  if (same.length < threshold) return false;
  const recent = same.slice(-threshold);
  const allUp = recent.every((e) => e.signal === 1);
  const allDown = recent.every((e) => e.signal === -1);
  if (!allUp && !allDown) return false;
  let weight = 0;
  for (let i = 1; i <= recent.length; i += 1) weight += 1 / i;
  const confidence = Math.min(0.8, weight / threshold);
  if (allUp) {
    await profile.update({
      receptive_dimensions: [target],
      inquiry_style: { primary: target, secondary: "unknown", confidence }
    });
  } else {
    await profile.update({ resistant_dimensions: [target] });
  }
  return true;
}

// src/feedback/index.ts
var MS_PER_DAY2 = 864e5;
function registerFeedback(ctx, config, profile) {
  const path = join4(expandHome(config.dataRoot), "feedback.json");
  let prunedTotal = 0;
  async function load() {
    try {
      const parsed = JSON.parse(await readFile3(path, "utf8"));
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }
  async function save(entries) {
    await mkdir3(dirname2(path), { recursive: true });
    await writeFile3(path, JSON.stringify(entries, null, 2) + "\n", "utf8");
  }
  async function loadPruned() {
    const entries = await load();
    const cutoff = now() - config.feedbackRetentionDays * MS_PER_DAY2;
    const kept = entries.filter((e) => typeof e.created_at === "number" && e.created_at >= cutoff);
    const dropped = entries.length - kept.length;
    if (dropped > 0) {
      prunedTotal += dropped;
      await save(kept);
      ctx.logger?.info?.(
        config.logPrefix + " feedback \u4FDD\u7559\u671F\u88C1\u526A\uFF1A%d \u6761\u8D85\u8FC7 %d \u5929",
        dropped,
        config.feedbackRetentionDays
      );
    }
    return kept;
  }
  ctx.effect(() => () => {
  }, "oblivion-core: feedback teardown");
  return {
    async record(args) {
      const entries = await loadPruned();
      const recorded = {
        id: newId(),
        target: args.target,
        signal: args.signal,
        context: args.context ?? "",
        created_at: now()
      };
      entries.push(recorded);
      await save(entries);
      const tuned = args.signal !== 0 ? await tune(entries, args.target, profile, config.feedbackTuneThreshold) : false;
      return { recorded, tuned };
    },
    all: loadPruned,
    reset: () => save([]),
    stats: async () => ({
      total: (await loadPruned()).length,
      pruned: prunedTotal,
      retentionDays: config.feedbackRetentionDays
    })
  };
}

// src/profile/schema.ts
function defaultProfile() {
  return {
    inquiry_style: { primary: "unknown", secondary: "unknown", confidence: 0 },
    followup_patterns: [],
    blind_spots: [],
    receptive_dimensions: [],
    resistant_dimensions: [],
    language_style: { tone: "neutral", prefers: [], dislikes: [] },
    active_goals: [],
    sessions_observed: 0
  };
}
function union(a = [], b = []) {
  return [.../* @__PURE__ */ new Set([...a, ...b])].slice(0, 40);
}
function mergeProfile(cur, signal) {
  return {
    ...cur,
    ...signal,
    inquiry_style: { ...cur.inquiry_style, ...signal.inquiry_style ?? {} },
    language_style: { ...cur.language_style, ...signal.language_style ?? {} },
    followup_patterns: union(cur.followup_patterns, signal.followup_patterns),
    blind_spots: union(cur.blind_spots, signal.blind_spots),
    receptive_dimensions: union(cur.receptive_dimensions, signal.receptive_dimensions),
    resistant_dimensions: union(cur.resistant_dimensions, signal.resistant_dimensions),
    active_goals: union(cur.active_goals, signal.active_goals),
    sessions_observed: Math.max(cur.sessions_observed, signal.sessions_observed ?? 0)
  };
}

// src/profile/index.ts
function extractStyleSignal(qa) {
  const q = qa.question;
  const evidence = [
    { dim: "mechanism", hit: /为什么|原理|机制|why|how does|internals/i.test(q) },
    { dim: "procedure", hit: /怎么|如何|步骤|流程|how to|guide/i.test(q) },
    { dim: "decision", hit: /选|对比|哪个|取舍|trade-?off|versus|\bvs\b/i.test(q) },
    { dim: "risk", hit: /风险|问题|坑|失败|会不会|risk|fail/i.test(q) },
    { dim: "design", hit: /设计|架构|拆分|重构|design|architect/i.test(q) }
  ];
  const hits = evidence.filter((e) => e.hit);
  const confidence = Math.min(0.5, hits.length * 0.15);
  const primary = hits[0]?.dim ?? "unknown";
  return {
    confidence,
    patch: {
      inquiry_style: { primary, secondary: hits[1]?.dim ?? "unknown", confidence },
      language_style: {
        tone: "terse",
        prefers: qa.answer.length > 1200 ? ["detail"] : ["concise"],
        dislikes: []
      },
      followup_patterns: q.split("\n").length > 3 ? ["multi-part question"] : []
    }
  };
}

// src/perspective/adapter.ts
function adaptStyle(perspectives, profile) {
  if (perspectives.length === 0) return "";
  const wantsDetail = profile.language_style.prefers.includes("detail");
  const lines = perspectives.map((p) => wantsDetail ? "- " + p.text + "\uFF08\u53EF\u5C55\u5F00\uFF09" : "- " + p.text);
  return ["## \u{1F9ED} \u6269\u5C55\u601D\u8003", ...lines].join("\n");
}

// src/perspective/maker.ts
function generatePerspectives(input) {
  const { coverage, misses, config, resistant, stage, deep } = input;
  const limit = Math.max(1, input.max ?? config.maxPerspectivePerTurn);
  const threshold = deep ? 1 : config.perspectiveMinMisses;
  const out = [];
  for (const dim of coverage.missing) {
    if (resistant.includes(dim)) continue;
    const count = misses.get(dim) ?? 0;
    if (count >= threshold) {
      out.push({
        kind: "missing-dimension",
        dimension: dim,
        text: "\u8FD9\u6761\u56DE\u7B54\u6CA1\u6709\u8986\u76D6\u300C" + dim + "\u300D\uFF0C\u800C\u5B83\u5728\u4F60\u6700\u8FD1\u7684\u63D0\u95EE\u91CC\u53CD\u590D\u51FA\u73B0\uFF08" + count + " \u6B21\uFF09\u3002"
      });
    }
  }
  if (deep) {
    for (const dim of coverage.missing) {
      if (out.length >= limit) break;
      if (resistant.includes(dim)) continue;
      if (out.some((p) => p.dimension === dim)) continue;
      out.push({
        kind: "unexplored",
        dimension: dim,
        text: "\u4F60\u8FDE\u7740\u51E0\u8F6E\u90FD\u5728\u540C\u4E00\u4E2A\u7EF4\u5EA6\u4E0A\u8FFD\u95EE\uFF0C\u8FD9\u6761\u56DE\u7B54\u6CA1\u6709\u8986\u76D6\u300C" + dim + "\u300D\u2014\u2014\u6362\u4E2A\u89D2\u5EA6\u770B\u770B\u4F1A\u4E0D\u4F1A\u66F4\u5FEB\u3002"
      });
    }
  }
  if (stage === "observe" && !deep) return out.slice(0, 1);
  if (out.length === 0 && stage === "companion" && coverage.missing.length === 0) {
    out.push({
      kind: "unexplored",
      dimension: "cost",
      text: "\u8FD9\u6B21\u7684\u8986\u76D6\u9762\u6BD4\u8F83\u5B8C\u6574\uFF0C\u552F\u4E00\u6CA1\u78B0\u7684\u662F\u957F\u671F\u6210\u672C\u3002"
    });
  }
  return out.slice(0, limit);
}

// src/perspective/tracker.ts
var DIMENSIONS = [
  "mechanism",
  "procedure",
  "decision",
  "risk",
  "design",
  "cost",
  "maintenance"
];
function pattern(dim) {
  switch (dim) {
    case "mechanism":
      return /原理|机制|因为|所以|根因|mechanism|because/i;
    case "procedure":
      return /步骤|流程|先.*然后|最后|step|first|then/i;
    case "decision":
      return /对比|取舍|权衡|优缺|trade-?off|\bvs\b/i;
    case "risk":
      return /风险|隐患|会失败|坑|risk|danger|failure/i;
    case "design":
      return /架构|分层|模块|接口|design|architect|module/i;
    case "cost":
      return /成本|开销|费用|性能|代价|cost|overhead|latency/i;
    case "maintenance":
      return /维护|升级|迁移|兼容|maintain|upgrade|migrat/i;
  }
}
function analyzeCoverage(question, answer, topic, sessionId) {
  const blob = question + "\n" + answer;
  const covered = [];
  const missing = [];
  for (const dim of DIMENSIONS) {
    if (pattern(dim).test(blob)) covered.push(dim);
    else missing.push(dim);
  }
  return { topic, session_id: sessionId, covered, missing, created_at: Date.now() };
}

// src/perspective/index.ts
function registerPerspective(ctx, config, deps) {
  let queued = "";
  const misses = /* @__PURE__ */ new Map();
  const resistance = /* @__PURE__ */ new Map();
  const records = [];
  let consecutiveDeepDives = 0;
  let lastPrimaryDimension;
  let sameDimensionStreak = 0;
  let sessionQueued = 0;
  const counters = {
    turns: 0,
    queued: 0,
    activeGateHits: 0,
    deepGateHits: 0,
    companionGateHits: 0,
    blockedByConfidence: 0
  };
  function stageOf(n) {
    if (n < config.perspectiveMinSessions) return "observe";
    if (n <= 10) return "probe";
    return "companion";
  }
  function dominantMissing(coverage, resistant) {
    return coverage.missing.find((d) => !resistant.includes(d));
  }
  ctx.effect(() => () => {
    queued = "";
    misses.clear();
    resistance.clear();
    records.length = 0;
    consecutiveDeepDives = 0;
    lastPrimaryDimension = void 0;
    sameDimensionStreak = 0;
    sessionQueued = 0;
  }, "oblivion-core: perspective teardown");
  return {
    pending: () => queued,
    takePending: () => {
      const t = queued;
      queued = "";
      return t;
    },
    async onTurn(info) {
      if (!config.enablePerspective) return;
      counters.turns += 1;
      const profile = await deps.profile.read();
      if (profile.inquiry_style.confidence < config.perspectiveMinConfidence) {
        counters.blockedByConfidence += 1;
        return;
      }
      const coverage = analyzeCoverage(info.question, info.answer, info.topic, info.sessionId);
      records.push(coverage);
      if (records.length > 200) records.shift();
      for (const dim of coverage.missing) {
        misses.set(dim, (misses.get(dim) ?? 0) + 1);
      }
      const resistant = [...resistance.entries()].filter(([, n]) => n >= 2).map(([d]) => d);
      const primary = dominantMissing(coverage, resistant);
      if (primary !== void 0 && primary === lastPrimaryDimension) {
        sameDimensionStreak += 1;
      } else {
        lastPrimaryDimension = primary;
        sameDimensionStreak = primary === void 0 ? 0 : 1;
      }
      const deepSignals = (info.question.match(/\n[-*\d]/g) ?? []).length + (info.question.length > 400 ? 1 : 0);
      consecutiveDeepDives = deepSignals >= 2 ? consecutiveDeepDives + 1 : 0;
      const deepGate = (sameDimensionStreak >= config.perspectiveDeepTriggerRepeats || consecutiveDeepDives >= config.perspectiveDeepDiveTurns) && sessionQueued < config.perspectiveDeepSessionMax;
      const activeGate = profile.sessions_observed <= config.perspectiveActiveSessionMax && info.question.trim().length >= config.perspectiveMinQuestionLength && (info.sources ?? 1) >= 1;
      const stage = stageOf(profile.sessions_observed);
      const companionGate = stage === "companion" && [...misses.values()].some((n) => n >= config.perspectiveMinMisses);
      if (!deepGate && !activeGate && !companionGate) return;
      if (deepGate) counters.deepGateHits += 1;
      else if (activeGate) counters.activeGateHits += 1;
      else counters.companionGateHits += 1;
      const wantCandidates = deepGate ? Math.max(config.perspectiveDeepMinCandidates, config.maxPerspectivePerTurn) : config.maxPerspectivePerTurn;
      const perspectives = generatePerspectives({
        profile,
        coverage,
        misses,
        config,
        stage,
        resistant,
        max: wantCandidates,
        deep: deepGate
      });
      if (perspectives.length === 0 && consecutiveDeepDives >= config.perspectiveDeepDiveTurns) {
        perspectives.push({
          kind: "to-verify",
          dimension: "assumption",
          text: "\u8FDE\u7EED\u6DF1\u6316\u82E5\u5E72\u8F6E\u4E86\uFF0C\u662F\u5426\u8BE5\u56DE\u5934\u9A8C\u8BC1\u4E00\u4E2A\u524D\u7F6E\u5047\u8BBE\uFF1F"
        });
      }
      const text = adaptStyle(perspectives, profile);
      if (text) {
        queued = text;
        sessionQueued += 1;
        counters.queued += 1;
      }
    },
    recordResistance: (dimension) => {
      resistance.set(dimension, (resistance.get(dimension) ?? 0) + 1);
    },
    coverage: () => [...records],
    stats: () => ({ ...counters })
  };
}

// src/stats/summary.ts
function ratio(part, whole) {
  return whole <= 0 ? 0 : Math.round(part / whole * 1e3) / 1e3;
}
function percentile(sorted, p) {
  if (sorted.length === 0) return 0;
  const idx = Math.min(sorted.length - 1, Math.max(0, Math.ceil(p / 100 * sorted.length) - 1));
  return Math.round(sorted[idx] * 1e3) / 1e3;
}
function summarize(records, config, windowDays = 0) {
  const byAction = {};
  const byReason = {};
  const scores = [];
  let captured = 0;
  let noQa = 0;
  let belowThreshold = 0;
  for (const record of records) {
    byAction[record.action] = (byAction[record.action] ?? 0) + 1;
    const reason = record.reason || "(none)";
    byReason[reason] = (byReason[reason] ?? 0) + 1;
    if (record.action === "no-qa") {
      noQa += 1;
      continue;
    }
    if (record.pass) captured += 1;
    if (typeof record.score === "number") {
      scores.push(record.score);
      if (!record.pass) belowThreshold += 1;
    }
  }
  const evaluated = records.length - noQa;
  scores.sort((a, b) => a - b);
  const ats = records.map((r) => r.at).filter((v) => typeof v === "number");
  return {
    windowDays,
    firstAt: ats.length ? Math.min(...ats) : null,
    lastAt: ats.length ? Math.max(...ats) : null,
    turns: records.length,
    evaluated,
    noQa,
    captured,
    rejected: evaluated - captured,
    captureRate: ratio(captured, evaluated),
    byAction,
    byReason,
    score: scores.length ? {
      min: Math.round(scores[0] * 1e3) / 1e3,
      p50: percentile(scores, 50),
      p90: percentile(scores, 90),
      max: Math.round(scores[scores.length - 1] * 1e3) / 1e3,
      belowThreshold
    } : null,
    thresholds: {
      valueThreshold: config.valueThreshold,
      semanticThreshold: config.semanticThreshold,
      minAnswerLength: config.minAnswerLength
    }
  };
}
function topReason(summary) {
  const entries = Object.entries(summary.byReason).sort((a, b) => b[1] - a[1]);
  return entries.length ? entries[0] : null;
}
function round(value, digits = 2) {
  const f = Math.pow(10, digits);
  return Math.round(value * f) / f;
}
function suggest(summary, config, extra = {}) {
  const minSample = extra.minSample ?? 20;
  const hints = [];
  if (summary.evaluated < minSample) return hints;
  const top = topReason(summary);
  const share = (reason) => Math.round((summary.byReason[reason] ?? 0) / summary.evaluated * 1e3) / 1e3;
  if (summary.captureRate < 0.05) {
    if (top && top[0].includes("below value threshold")) {
      hints.push({
        key: "valueThreshold",
        current: config.valueThreshold,
        suggested: round(Math.max(0.15, config.valueThreshold - 0.05)),
        why: "\u6355\u83B7\u7387 " + summary.captureRate + "\uFF0C\u4E14\u5927\u591A\u88AB\u4EF7\u503C\u5C42\u62E6\u4E0B\uFF08" + share(top[0]) + "\uFF09\u3002\u5F53\u524D\u9608\u503C " + config.valueThreshold + " \u504F\u9AD8\uFF0C\u53EF\u5148\u964D 0.05 \u89C2\u5BDF\u51E0\u5929\u3002"
      });
    } else if (top && top[0] === "answer-too-short") {
      hints.push({
        key: "minAnswerLength",
        current: config.minAnswerLength,
        suggested: 1,
        why: "\u6355\u83B7\u7387 " + summary.captureRate + "\uFF0C\u4E14\u5927\u591A\u56E0\u300C\u7B54\u6848\u592A\u77ED\u300D\u88AB L3 \u62E6\u4E0B\uFF08" + share(top[0]) + "\uFF09\u3002\u82E5\u4F60\u5E38\u95EE\u300C\u662F/\u5426\u300D\u578B\u77ED\u95EE\u9898\uFF0C\u628A minAnswerLength \u8C03\u5230 1\uFF08\u4EA4\u7ED9\u4EF7\u503C\u5C42\u5224\u65AD\uFF09\u3002"
      });
    } else if (top && top[0] === "exact hash match") {
      hints.push({
        key: "semanticThreshold",
        current: config.semanticThreshold,
        why: "\u6355\u83B7\u7387\u4F4E\u4E3B\u8981\u662F**\u5B8C\u5168\u91CD\u590D**\u63D0\u95EE\uFF08" + share(top[0]) + "\uFF09\u2014\u2014 \u8FD9\u662F\u6B63\u5E38\u73B0\u8C61\uFF0C\u4E0D\u5FC5\u8C03\u53C2\u3002"
      });
    }
  }
  if (summary.score && summary.score.p50 > 0) {
    const gap = config.valueThreshold - summary.score.p50;
    if (Math.abs(gap) <= 0.05) {
      hints.push({
        key: "valueThreshold",
        current: config.valueThreshold,
        suggested: round(round(config.valueThreshold + (gap >= 0 ? -0.05 : 0.05))),
        why: "\u4EF7\u503C\u5206\u4E2D\u4F4D\u6570 " + summary.score.p50 + " \u7D27\u8D34\u9608\u503C " + config.valueThreshold + "\uFF08p90=" + summary.score.p90 + "\uFF09\u2014\u2014\u9608\u503C\u6B63\u843D\u5728\u5206\u5E03\u4E2D\u592E\uFF0C\xB10.05 \u5C31\u4F1A\u660E\u663E\u6539\u53D8\u6355\u83B7\u91CF\u3002"
      });
    }
  }
  if (typeof extra.perspectiveQueued === "number" && summary.evaluated >= minSample) {
    const perTurn = extra.perspectiveQueued / summary.evaluated;
    if (extra.perspectiveQueued === 0) {
      hints.push({
        key: "perspectiveActiveSessionMax / perspectiveMinConfidence",
        current: {
          perspectiveActiveSessionMax: config.perspectiveActiveSessionMax,
          perspectiveMinConfidence: config.perspectiveMinConfidence
        },
        why: summary.evaluated + " \u4E2A\u53EF\u8BC4\u4F30\u8F6E\u91CC\u966A\u4F34\u4E00\u6B21\u90FD\u6CA1\u89E6\u53D1\u3002\u82E5\u4F60\u5E0C\u671B\u5B83\u5F00\u53E3\uFF0C\u5148\u770B\u6863\u6848\u7F6E\u4FE1\u5EA6\u662F\u5426 \u2265 " + config.perspectiveMinConfidence + "\uFF08\u65B0\u5E93\u901A\u5E38\u4E0D\u591F\uFF09\uFF0C\u6216\u628A perspectiveActiveSessionMax \u8C03\u5927\uFF08\u4E3B\u52A8\u901A\u9053\u53EA\u5728\u6700\u65E9\u51E0\u6B21\u4F1A\u8BDD\u5F00\u95E8\uFF09\u3002"
      });
    } else if (perTurn > 0.3) {
      hints.push({
        key: "maxPerspectivePerTurn / perspectiveMinMisses",
        current: { maxPerspectivePerTurn: config.maxPerspectivePerTurn, perspectiveMinMisses: config.perspectiveMinMisses },
        why: "\u966A\u4F34\u89E6\u53D1\u7387 " + round(perTurn) + "\uFF08\u6BCF\u6B21\u53EF\u8BC4\u4F30\u8F6E\uFF09\uFF0C\u504F\u9AD8\u3002\u53EF\u628A perspectiveMinMisses \u8C03\u5927\u6216 maxPerspectivePerTurn \u8C03\u5230 1\u3002"
      });
    }
  }
  return hints;
}

// src/stats/trace.ts
import { appendFile as appendFile2, mkdir as mkdir4, readFile as readFile4, writeFile as writeFile4 } from "node:fs/promises";
import { dirname as dirname3, join as join5 } from "node:path";
function createTraceStore(dataRoot, options) {
  const path = join5(dataRoot, "decisions.jsonl");
  const MS_PER_DAY3 = 864e5;
  async function readRaw() {
    try {
      const raw = await readFile4(path, "utf8");
      const out = [];
      for (const line of raw.split("\n")) {
        const trimmed = line.trim();
        if (trimmed === "") continue;
        try {
          out.push(JSON.parse(trimmed));
        } catch {
        }
      }
      return out;
    } catch {
      return [];
    }
  }
  return {
    path,
    async record(entry) {
      try {
        await mkdir4(dirname3(path), { recursive: true });
        await appendFile2(path, JSON.stringify(entry) + "\n", "utf8");
      } catch (error) {
        options.logger?.warn?.(String(options.logPrefix ?? "") + " \u5224\u5B9A\u7559\u75D5\u5199\u5165\u5931\u8D25\uFF1A%o", error);
      }
    },
    async read(limit) {
      const all = await readRaw();
      const cutoff = now() - options.retentionDays * MS_PER_DAY3;
      const fresh = all.filter((entry) => typeof entry.at === "number" && entry.at >= cutoff);
      const kept = fresh.length > options.maxEntries ? fresh.slice(fresh.length - options.maxEntries) : fresh;
      if (kept.length !== all.length) {
        try {
          await writeFile4(path, kept.map((entry) => JSON.stringify(entry)).join("\n") + (kept.length ? "\n" : ""), "utf8");
        } catch (error) {
          options.logger?.warn?.(String(options.logPrefix ?? "") + " \u5224\u5B9A\u7559\u75D5\u88C1\u526A\u843D\u76D8\u5931\u8D25\uFF1A%o", error);
        }
      }
      return typeof limit === "number" && limit > 0 ? kept.slice(kept.length - limit) : kept;
    }
  };
}

// src/stats/index.ts
import { writeFile as writeFile5, mkdir as mkdir5 } from "node:fs/promises";
import { dirname as dirname4, join as join6 } from "node:path";
function registerStats(ctx, config, meta) {
  const dataRoot = expandHome(config.dataRoot);
  const trace = createTraceStore(dataRoot, {
    retentionDays: config.statsRetentionDays,
    maxEntries: config.statsMaxEntries,
    logger: ctx.logger,
    logPrefix: config.logPrefix
  });
  ctx.effect(() => () => {
  }, "oblivion-core: stats teardown");
  async function summary() {
    const records = await trace.read();
    return summarize(records, config, config.statsRetentionDays);
  }
  return {
    tracePath: trace.path,
    record: (entry) => trace.record(entry),
    read: (limit) => trace.read(limit),
    summary,
    async status(options = {}) {
      const records = await trace.read();
      const stats = summarize(records, config, config.statsRetentionDays);
      const perspective = options.perspective ?? {};
      return {
        version: meta.version,
        generatedAt: now(),
        dataRoot,
        mdRoot: expandHome(config.mdRoot),
        config,
        hints: suggest(stats, config, {
          perspectiveQueued: typeof perspective.queued === "number" ? perspective.queued : void 0
        }),
        stats,
        recent: records.slice(-(options.recentLimit ?? 20)),
        perspective,
        tracePath: trace.path
      };
    },
    async writeBootSnapshot(extra) {
      try {
        const path = join6(dataRoot, "status.json");
        await mkdir5(dirname4(path), { recursive: true });
        const stats = await summary();
        const payload = {
          version: meta.version,
          generatedAt: now(),
          dataRoot,
          mdRoot: expandHome(config.mdRoot),
          config,
          stats,
          hints: suggest(stats, config),
          tracePath: trace.path,
          ...extra
        };
        await writeFile5(path, JSON.stringify(payload, null, 2) + "\n", "utf8");
        return;
      } catch (error) {
        ctx.logger?.warn?.(config.logPrefix + " status.json \u5199\u5165\u5931\u8D25\uFF1A%o", error);
      }
    }
  };
}

// src/config.ts
var DEFAULT_CONFIG = {
  dataRoot: "~/.oblivion/data",
  /**
   * 文档根（所有者裁定 2026-10-06）：直接写进既有的知识库，不再单开 `oblivion_docs/`。
   * 用正斜杠书写：Windows 上 `path.isAbsolute('C:/…')` 成立，`expandHome()` 原样放行，
   * 且写进 YAML 时不需要转义反斜杠。
   */
  mdRoot: "C:/Library/\u90A3\u4E9B\u6E10\u6E10\u88AB\u9057\u5FD8",
  mdClassify: {
    // 问答沉淀（我们的捕获来源是 session；qa_loop 是设计书的原始命名，一并兼容）
    session: "01_\u95EE\u7B54\u6C89\u6DC0",
    qa_loop: "01_\u95EE\u7B54\u6C89\u6DC0",
    // 设计书 §25.3 的其余分类（后续文档导入/创作能力落地后直接生效）
    doc: "00_\u5BFC\u5165\u6587\u4EF6",
    wiki: "02_Wiki\u9875\u9762",
    content_creator: "03_\u521B\u4F5C\u4EA7\u7269"
  },
  /**
   * 价值阈值 —— **已按实测重标定，不要改回设计书原值 0.5**。
   *
   * 实测分布（heuristicScore）：
   *   真实 233 字技术回答（有来源 + 结构 + 代码）  0.370
   *   500 字普通回答                              ~0.42
   *   900 字低信息密度（大量重复）                 0.454
   *   "ok"                                      0.113
   *
   * 原值 0.5 落在「真实回答之上、重复文本之下」，会让正常问答**一律被丢弃**
   * ——症状是插件装好了但知识库永远为空，且不报错。0.30 把「ok 类噪声」
   * 挡住，同时放行正常回答。这是端到端自检用例抓出来的，改动请同步更新
   * test/ 与 scripts/selfcheck.mjs 的断言。
   */
  semanticThreshold: 0.85,
  valueThreshold: 0.3,
  enablePerspective: true,
  enableFeedback: true,
  perspectiveMinSessions: 4,
  perspectiveMinConfidence: 0.3,
  perspectiveMinMisses: 3,
  perspectiveDeepDiveTurns: 5,
  // §25.4 双模式闸门（设计书原值）
  perspectiveActiveSessionMax: 3,
  perspectiveMinQuestionLength: 10,
  perspectiveDeepTriggerRepeats: 3,
  perspectiveDeepMinCandidates: 3,
  perspectiveDeepSessionMax: 5,
  // §25.7 保留期（读取时惰性裁剪，满足「无定时任务」约束）
  feedbackRetentionDays: 90,
  graphInitialWeight: 0.3,
  graphReinforceDelta: 0.05,
  graphWeightCap: 1,
  graphDecayBase: 0.95,
  graphDecayPeriodDays: 30,
  feedbackTuneThreshold: 3,
  promptSectionOrder: 50,
  maxPerspectivePerTurn: 2,
  /**
   * L3 最低答案长度 —— **设计书 §25.1 原值 5**（旧实现用 20，等于把 L3 当成了价值闸门）。
   * 5 字以下直接判无意义；「短但可能有用」留给 L4 价值评估（`valueThreshold`）兜底。
   */
  minAnswerLength: 5,
  logPrefix: "[oblivion-core]",
  // 观测面（调参要靠真实数据：先跑够几天，再用 oblivion_status 看建议）
  enableStats: true,
  statsRetentionDays: 90,
  statsMaxEntries: 5e3,
  statusRecentLimit: 20,
  // 临时事件探针（链路验证通过后设 false）
  enableEventProbe: true,
  eventProbeMax: 200
};
function resolveConfig(input) {
  if (!input) return DEFAULT_CONFIG;
  const out = { ...DEFAULT_CONFIG };
  for (const [k, v] of Object.entries(input)) {
    if (v !== void 0 && v !== null) out[k] = v;
  }
  return out;
}
export {
  DEFAULT_CONFIG,
  DIMENSIONS,
  MD_FALLBACK_DIR,
  MS_PER_DAY,
  adaptStyle,
  ageDays,
  analyzeCoverage,
  checkL3Rules,
  classifyDir,
  compareByOverlap,
  createTraceStore,
  defaultProfile,
  deriveTitle,
  deriveTopic,
  effectiveWeight,
  ensureMdDirs,
  evaluate,
  expandHome,
  extractEntities,
  extractQAPair,
  extractStyleSignal,
  fourLayerFilter,
  generatePerspectives,
  heuristicScore,
  isHumanUserMessage,
  isOblivionOriginated,
  isoDate,
  jaccard,
  mdDirNames,
  mergeProfile,
  newId,
  normalizeForHash,
  registerFeedback,
  registerPerspective,
  registerQaLoop,
  registerStats,
  reinforce,
  resolveConfig,
  safeDirName,
  sha1,
  shortHash,
  suggest,
  summarize,
  textOfMessage,
  tokenize,
  tune,
  userMessageSourceKind,
  writeMD
};
